Osmia bicornis Population Model: Osmia_InCocoon Class Reference
Osmia_InCocoon Class Reference
Overwintering adult stage within cocoon.
#include <Osmia_enh_PART3_Final.h>
Public Member Functions
Osmia_InCocoon (struct_Osmia *data)
Constructor for newly eclosed adult in cocoon.
virtual void ReInit (struct_Osmia *data)
Reinitialize object from pool.
virtual ~Osmia_InCocoon ()
Destructor.
virtual void Step (void)
Main step function for overwintering adults.
double GetDDPreWinter ()
Get prewinter degree-day accumulation.
Public Member Functions inherited from Osmia_Pupa
Osmia_Pupa (struct_Osmia *data)
Constructor transferring from prepupa.
virtual ~Osmia_Pupa ()
Destructor.
Public Member Functions inherited from Osmia_Prepupa
Osmia_Prepupa (struct_Osmia *data)
Constructor transferring from larva to prepupa.
virtual ~Osmia_Prepupa ()
Destructor.
Public Member Functions inherited from Osmia_Larva
Osmia_Larva (struct_Osmia *data)
Constructor for new larva (created during egg hatching).
virtual ~Osmia_Larva ()
Destructor.
Public Member Functions inherited from Osmia_Egg
Osmia_Egg (struct_Osmia *data)
Constructor for new egg object.
virtual ~Osmia_Egg ()
Destructor.
double GetAgeDegrees ()
Get accumulated degree-days.
void SetAgeDegrees (unsigned a_agedegrees)
Set accumulated degree-days (used during object reinitialization).
Public Member Functions inherited from Osmia_Base
Osmia_Base (struct_Osmia *data)
Constructor creating new Osmia_Base individual.
void ReInit (struct_Osmia *data)
Reinitialize object from object pool.
virtual ~Osmia_Base ()
Virtual destructor ensuring proper cleanup in derived classes.
virtual void st_Dying (void)
Behavioural state for death - cleanup and removal.
virtual void BeginStep (void)
First phase of daily timestep.
virtual void EndStep (void)
Final phase of daily timestep.
int GetAge ()
Get individual's age in days.
void SetAge (int a_age)
Set individual's age in days.
double GetMass ()
Get individual's mass (mg) - interpretation depends on life stage.
void SetMass (double a_mass)
Set individual's mass (mg).
void SetParasitised (TTypeOfOsmiaParasitoids a_status)
Set parasitism status.
TTypeOfOsmiaParasitoids GetParasitised (void)
Get parasitism status.
Osmia_Nest * GetNest ()
Get pointer to nest containing or being provisioned by this individual.
Static Public Member Functions
static void SetOverwinteringTempThreshold (double a_temp)
Set overwintering temperature threshold (static parameter).
Static Public Member Functions inherited from Osmia_Base
static void SetParameterValues ()
Populate all static parameters from configuration file.
static void SetTemp (double a_temperature)
Set current daily temperature for all individuals.
static void SetParasitoidManager (OsmiaParasitoid_Population_Manager *a_popman)
Set parasitoid population manager pointer.
Protected Member Functions
virtual TTypeOfOsmiaState st_Develop (void)
Development state - manage overwintering phases and emergence preparation.
virtual TTypeOfOsmiaState st_Emerge (void)
Transition state - emerge from cocoon as active adult.
bool WinterMortality ()
Calculate overwintering mortality probability from prewinter thermal conditions.
Protected Member Functions inherited from Osmia_Pupa
virtual bool DailyMortality ()
Daily mortality test for pupae.
Protected Member Functions inherited from Osmia_Prepupa
virtual TTypeOfOsmiaState st_Pupate (void)
Transition state - metamorphose from prepupa to pupa.
Protected Member Functions inherited from Osmia_Larva
virtual TTypeOfOsmiaState st_Prepupate (void)
Transition state - metamorphose from larva to prepupa.
Protected Member Functions inherited from Osmia_Egg
virtual TTypeOfOsmiaState st_Hatch (void)
Transition state - metamorphose from egg to larva.
Protected Attributes
int m_emergencecounter
Countdown to spring emergence (decrements with warm days).
double m_DDPrewinter
Accumulated degree-days during prewintering period (above 15°C baseline).
Protected Attributes inherited from Osmia_Prepupa
double m_myOsmiaPrepupaDevelTotalDays
Individual-specific prepupal development duration (days).
Protected Attributes inherited from Osmia_Egg
double m_AgeDegrees = 0.0
Accumulated degree-days toward hatching threshold.
bool m_Sex
Sex of individual (true = female = fertilised egg).
int m_StageAge
Age in days when current life stage was entered.
double m_egg_pest_mortality
Cumulative pesticide mortality probability for this egg.
Protected Attributes inherited from Osmia_Base
TTypeOfOsmiaState m_CurrentOState
Current behavioural state governing agent decisions.
int m_Age
Chronological age in days since egg laying.
Osmia_Population_Manager * m_OurPopulationManager
Pointer to the Osmia population manager instance.
TTypeOfOsmiaParasitoids m_ParasitoidStatus
Records parasitism status of this individual.
Osmia_Nest * m_OurNest
Pointer to nest containing this individual.
double m_Mass
Mass of individual or provision (mg) - interpretation varies by life stage.
int m_foragehours
Hours available for foraging today (decremented as foraging proceeds).
Static Protected Attributes
static double m_OverwinteringTempThreshold = 0.0
Static temperature threshold for overwintering phase (°C).
Static Protected Attributes inherited from Osmia_Base
static OsmiaParasitoid_Population_Manager * m_OurParasitoidPopulationManager = NULL
Static pointer to parasitoid population manager (if using mechanistic parasitoid model).
static double m_TempToday = -9999
Mean daily temperature (°C) for current timestep.
static int m_TempTodayInt = -9999
Rounded integer temperature for array indexing.
static double m_DailyDevelopmentMortEggs = 0
Daily mortality probability for eggs (probability per day).
static double m_DailyDevelopmentMortLarvae = 0
Daily mortality probability for larvae (probability per day).
static double m_DailyDevelopmentMortPrepupae = 0
Daily mortality probability for prepupae (probability per day).
static double m_DailyDevelopmentMortPupae = 0
Daily mortality probability for pupae (probability per day).
static double m_OsmiaEggDevelTotalDD = 0
Total degree-days required for egg development to hatching.
static double m_OsmiaEggDevelThreshold = 0
Lower developmental threshold temperature for eggs (°C).
static double m_OsmiaLarvaDevelTotalDD = 0
Total degree-days required for larval development to prepupal stage.
static double m_OsmiaLarvaDevelThreshold = 0
Lower developmental threshold temperature for larvae (°C).
static double m_OsmiaPupaDevelTotalDD = 0
Total degree-days required for pupal development to adult eclosion.
static double m_OsmiaPupaDevelThreshold = 0
Lower developmental threshold temperature for pupae (°C).
static double m_OsmiaPrepupalDevelTotalDays = 0
Total days for prepupal development at optimal temperature.
static double m_OsmiaPrepupalDevelTotalDays10pct = 0
Pre-computed 10% of prepupal development time.
static double m_OsmiaInCocoonOverwinteringTempThreshold = 0
Temperature threshold (°C) for accumulating overwintering degree-days.
static double m_OsmiaInCocoonEmergenceTempThreshold = 0
Temperature threshold (°C) for post-diapause emergence counter.
static double m_OsmiaInCocoonPrewinteringTempThreshold = 0
Temperature threshold (°C) for accumulating prewintering degree-days.
static double m_OsmiaInCocoonWinterMortConst = 0.0
Intercept for overwintering mortality equation.
static double m_OsmiaInCocoonWinterMortSlope = 0.0
Slope for overwintering mortality equation.
static double m_OsmiaInCocoonEmergCountConst = 0.0
Intercept for emergence counter equation.
static double m_OsmiaInCocoonEmergCountSlope = 0.0
Slope for emergence counter equation.
static double m_OsmiaFemaleMassFromProvMassConst = 0.0
Intercept for calculating female mass from provision mass.
static double m_OsmiaFemaleMassFromProvMassSlope = 0.0
Slope for calculating female mass from provision mass.
static double m_MaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for male nest cells (mg).
static double m_MaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for male nest cells (mg).
static double m_FemaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxMass = 0.0
Maximum female adult mass (mg) - sets upper bound for provision mass calculations.
static double m_FemaleMinMass = 0.0
Minimum female adult mass (mg) - sets lower bound for provision mass calculations.
static double m_MaleMaxMass = 0.0
Maximum male adult mass (mg) - males are smaller than females.
static double m_PollenScoreToMg = 0.0
Conversion factor from pollen availability score to provisioned mass (mg pollen per day).
static double m_DensityDependentPollenRemovalConst = 0.0
Parameter linking pollen depletion to Osmia population density.
static double m_MinimumCellConstructionTime = 0.0
Minimum time (days) required to construct and provision one nest cell.
static double m_MaximumCellConstructionTime = 0.0
Maximum time (days) required to construct and provision one nest cell.
static int m_TotalNestsPossible = 0
Maximum number of nests a female can complete in her lifetime.
static double m_BombylidProbability = 0.0
Baseline probability of bombyliid fly parasitism per open nest cell.
static double m_ParasitismProbToTimeCellOpen = 0.0
Conversion factor relating cell open time (days) to parasitism probability.
static vector< double > m_ParasitoidAttackChance = {}
Per-capita parasitoid attack probabilities for mechanistic parasitoid model.
static double m_OsmiaFemaleR50distance = 0.0
Typical homing distance - distance at which 50% of females cannot return to nest (m).
static double m_OsmiaFemaleR90distance = 0.0
Maximum homing distance - distance at which 90% of females cannot return (m).
static int m_OsmiaFemalePrenesting = 0
Duration of prenesting period after emergence (days).
static int m_OsmiaFemaleLifespan = 0
Maximum adult female lifespan (days).
static probability_distribution m_generalmovementdistances = probability_distribution(cfg_OsmiaGeneralMovementProbType.value(), cfg_OsmiaGenerallMovementProbArgs.value())
Probability distribution for foraging and nest-searching movements.
static probability_distribution m_dispersalmovementdistances = probability_distribution(cfg_OsmiaDispersalMovementProbType.value(), cfg_OsmiaDispersalMovementProbArgs.value())
Probability distribution for dispersal movements (longer than foraging movements).
static probability_distribution m_eggspernestdistribution = probability_distribution(cfg_OsmiaEggsPerNestProbType.value(), cfg_OsmiaEggsPerNestProbArgs.value())
Probability distribution for planned eggs per nest.
static probability_distribution m_exp_ZeroToOne = probability_distribution("BETA", "1.0, 5.0")
Exponential-like probability distribution over range [0,1].
static double m_CocoonToProvisionMass = 0.0
Mass conversion ratio from cocoon mass to provision mass required.
static double m_ProvisionToCocoonMass = 0.0
Mass conversion ratio from provision mass to resulting cocoon mass.
static double m_TotalProvisioningMassLoss = 0.0
Total provision mass loss from first to last egg in a nest (mg).
static double m_TotalProvisioningMassLossRange = 0.0
Stochastic range around total provisioning mass loss (mg).
static double m_TotalProvisioningMassLossRangeX2 = 0.0
Pre-computed double of mass loss range for efficiency.
static bool m_UsingMechanisticParasitoids = false
Flag selecting parasitism model: true=mechanistic population model, false=simple probabilities.
static double m_OsmiaFemaleBckMort = 0.0
Daily background mortality for adult females outside nest (probability per day).
static int m_OsmiaFemaleMinEggsPerNest = 0
Minimum eggs planned per nest (sets lower bound for egg planning distribution).
static int m_OsmiaFindNestAttemptNo = 0
Number of attempts allowed for finding suitable nest location before giving up.
static int m_OsmiaFemaleMaxEggsPerNest = 0
Maximum eggs planned per nest (sets upper bound for egg planning distribution).
static probability_distribution m_emergenceday = probability_distribution(cfg_OsmiaEmergenceProbType.value(), cfg_OsmiaEmergenceProbArgs.value())
Probability distribution for day of emergence relative to population mean.
Detailed Description
Overwintering adult stage within cocoon.
Osmia_InCocoon represents the eclosed adult bee overwintering within its protective cocoon. This stage implements the three-phase overwintering model: prewintering (late summer/autumn at elevated temperatures), diapause proper (winter at low temperatures), and post-diapause quiescence (early spring awaiting emergence cues). Overwintering mortality depends on prewinter thermal conditions, and emergence timing is determined by an emergence counter that decrements with spring warming.
Biological Foundation
Adult O. bicornis eclose from pupae in late summer (August-September) but remain within cocoons through winter, emerging the following spring (April-May). This overwintering strategy protects adults from winter weather whilst avoiding energetic costs of maintaining activity. The three-phase model reflects documented physiological transitions: initial high respiration rates during prewintering deplete fat reserves if warm conditions persist, deep diapause conserves energy through winter, and post-diapause quiescence awaits appropriate emergence conditions.
Three-Phase Overwintering Model
Phase 1 - Prewintering (typically September-November):
Occurs at temperatures above prewintering threshold (15°C)
Accumulates degree-days (m_DDPrewinter) that increase mortality risk
Represents fat depletion at warm temperatures
Based on Sgolastra et al. (2011) work with O. lignaria
Phase 2 - Diapause (typically November-January):
Deep dormancy at temperatures near/below overwintering threshold (0°C)
Minimal metabolic activity, lipid conservation
No degree-day accumulation during this phase
Chilling requirement for diapause completion (not explicitly modelled as separate counter)
Phase 3 - Post-diapause quiescence (typically February-March):
Diapause complete but awaiting emergence cues
Emergence counter decrements with temperatures above emergence threshold (5°C)
When counter reaches zero, adult emerges from nest
Counter equation: 35.48 - 0.0147 × DD_accumulated
Overwintering Mortality
Calculated as function of prewinter degree-day accumulation using equation from Sgolastra et al. (2011): mortality_probability = 0.05 × DD_prewinter - 4.63
This captures the biological reality that prolonged warm autumn conditions deplete lipid reserves, reducing winter survival. Cool autumn conditions (low DD accumulation) produce high survival.
Difference from Formal Model
EXACT MATCH for equations - Overwintering mortality and emergence counter equations implemented precisely as specified in formal model. Temperature thresholds match formal model specifications (0°C overwintering, 5°C emergence, 15°C prewintering baseline).
Minor calibration: Emergence counter constant adjusted from 39.48 to 35.48, shifting emergence timing slightly earlier in spring to match field observations.
Implementation Notes
The three phases are not explicitly flagged as separate states - rather, they emerge from temperature- threshold logic applied to DD accumulation and counter updates. This creates appropriate seasonal phenology without needing complex state tracking.
See also
Osmia_Base for overwintering parameters
st_Develop() for phase transition logic
WinterMortality() for mortality calculation
st_Emerge() for spring emergence
Definition at line 65 of file Osmia_enh_PART3_Final.h.
Constructor & Destructor Documentation
Osmia_InCocoon()
Osmia_InCocoon::Osmia_InCocoon (struct_Osmia * data)
Constructor for newly eclosed adult in cocoon.
Constructor for Osmia_InCocoon from initialization data.
Parameters
data Initialization data from pupal stage
Initializes overwintering-specific attributes:
Sets m_DDPrewinter to 0 (begins accumulation from eclosion)
Calculates initial m_emergencecounter from current conditions
Transfers adult mass from pupal provision mass
Maintains nest linkage for eventual emergence
Creates a pharate adult within cocoon that will overwinter and potentially emerge in spring. Initializes emergence counter and degree-day accumulators.
Parameters
data Pointer to struct_Osmia containing initialization data
Biological Context
Osmia_InCocoon represents the overwintering stage: fully formed adults within sealed cocoons experiencing winter dormancy. This stage typically lasts from late summer/early autumn (August-September when pupal development completes) through winter until spring emergence (March-May). Individuals face temperature-dependent winter mortality and must accumulate appropriate thermal and temporal cues for properly timed spring emergence.
Overwintering Phases
The stage comprises three distinct phases:
Prewintering (late summer/autumn): Pharate adults accumulate pre-winter degree-days above 15°C threshold. This represents final metabolic preparation before winter dormancy.
Overwintering (winter): Adults accumulate overwintering degree-days above 0°C threshold. Accumulation increases winter mortality probability via the linear mortality equation.
Pre-emergence (late winter/spring): Starting March 1st, adults count days above 5°C threshold towards an emergence counter. When counter reaches zero, emergence occurs.
Developmental Model
Unlike earlier stages, Osmia_InCocoon uses a complex multi-phase model combining degree-day accumulation (prewintering, overwintering) with a temperature-time counter (emergence). This complexity reflects the biological reality that spring emergence requires both sufficient thermal accumulation and appropriate phenological timing, preventing emergence during brief winter warm spells whilst ensuring synchronisation with spring flowering.
Implementation Strategy
Inherits from Osmia_Pupa, accessing the full state variable structure. However, the developmental mechanism diverges completely from degree-day based progression, implementing phase-specific logic in st_Develop(). The emergence counter (m_emergencecounter) starts at an impossibly large value, recalculated appropriately on March 1st based on accumulated winter degree-days.
See also
st_Develop() for phase-specific overwintering logic
WinterMortality() for temperature-dependent winter mortality calculation
Definition at line 2553 of file Osmia_dox.cpp.
References m_DDPrewinter, m_emergencecounter, Osmia_Pupa::Osmia_Pupa(), and ReInit().
~Osmia_InCocoon()
Osmia_InCocoon::~Osmia_InCocoon (void) virtual
Destructor.
Destructor for Osmia_InCocoon.
Empty destructor as cleanup is handled by base classes. Overwintering adults either die during winter or emerge in spring as active adults (Osmia_Female).
Definition at line 2509 of file Osmia_dox.cpp.
Member Function Documentation
GetDDPreWinter()
double Osmia_InCocoon::GetDDPreWinter () inline
Get prewinter degree-day accumulation.
Returns
Total DD accumulated above 15°C baseline during prewintering
Accessor for monitoring overwintering conditions and mortality risk. Used in output generation and validation.
Definition at line 162 of file Osmia_enh_PART3_Final.h.
References m_DDPrewinter.
ReInit()
void Osmia_InCocoon::ReInit (struct_Osmia * data) virtual
Reinitialize object from pool.
Reinitialize an existing Osmia_InCocoon object with new data.
Parameters
data New initialization data
Chains to Osmia_Pupa::ReInit() and adds InCocoon-specific initialization. Supports population initialization scenarios where individuals begin simulation as overwintering adults.
Parameters
data Pointer to struct_Osmia containing new initialization data, including optional overwintering_degree_days for mid-winter initialization
Implementation Notes
The emergence counter is set to an impossibly large value (99999) initially, then calculated properly on March 1st based on accumulated overwintering degree-days. The prewintering degree-day accumulator (m_DDPrewinter) starts at zero. If initializing mid-winter, overwintering degree-days (m_AgeDegrees) can be specified in the initialization structure.
Reimplemented from Osmia_Pupa.
Reimplemented in Osmia_Female.
Definition at line 2496 of file Osmia_dox.cpp.
References Osmia_Egg::m_AgeDegrees, m_DDPrewinter, m_emergencecounter, struct_Osmia::overwintering_degree_days, and Osmia_Pupa::ReInit().
Referenced by Osmia_InCocoon().
SetOverwinteringTempThreshold()
void Osmia_InCocoon::SetOverwinteringTempThreshold (double a_temp) inline static
Set overwintering temperature threshold (static parameter).
Parameters
a_temp Temperature threshold (°C) for overwintering DD accumulation
Used primarily during initialization to set population-wide threshold from configuration.
Definition at line 154 of file Osmia_enh_PART3_Final.h.
References m_OverwinteringTempThreshold.
st_Develop()
TTypeOfOsmiaState Osmia_InCocoon::st_Develop (void) protected virtual
Development state - manage overwintering phases and emergence preparation.
Execute daily overwintering development, managing phase-specific logic.
Returns
Next state (st_Emerge when ready, st_Develop to continue, or st_Die)
Complex multi-phase logic:
Prewintering phase (warm autumn conditions):
If T > 15°C: accumulate to m_DDPrewinter
Represents fat depletion period
No explicit phase flag - identified by temperature
Diapause phase (winter cold):
Temperatures near/below 0°C
Minimal DD accumulation
Lipid conservation
No active tracking - just waiting period
Post-diapause phase (spring warming):
If T > 5°C (emergence threshold): decrement m_emergencecounter
Counter -= (T - threshold)
When counter ≤ 0: ready to emerge
Check for favorable conditions (appropriate temperature, daylight)
Mortality application:
Call WinterMortality() to calculate probability from prewinter DD
Test against random number
If dies: return st_Die
If survives and counter ≤ 0: return st_Emerge
Otherwise: return st_Develop (continue overwintering)
Temperature Threshold Handling
Three thresholds govern different processes:
15°C: Prewinter DD accumulation (represents elevated metabolism)
5°C: Emergence counter (spring warming required)
0°C: Overwintering baseline (diapause maintenance)
These thresholds create realistic seasonal phenology without explicit calendar tracking.
Edge Cases
Very warm autumn (high prewinter DD): High mortality, survivors may emerge earlier
Very cold autumn (low prewinter DD): High survival, emergence depends more on spring warming
Warm winter spell: May decrement emergence counter but doesn't trigger premature emergence (counter must reach zero AND appropriate conditions must persist)
Difference from Formal Model
IMPLEMENTATION MATCH - The logic structure follows formal model three-phase description. Temperature thresholds and equations match specifications. The implementation detail of using continuous threshold checks rather than explicit phase flags is consistent with formal model emphasis on emergent behaviour from temperature-threshold interactions.
Implements three-phase overwintering model: prewintering degree-day accumulation, winter degree-day accumulation affecting mortality, and pre-emergence counter mechanism determining spring emergence timing.
Returns
Next state: toOsmias_Die if late-season emergence deadline passed, toOsmias_NextStage if emergence counter reaches zero, toOsmias_Develop to continue overwintering
Phase 1: Prewintering (Late Summer/Autumn)
Before the population manager signals end of prewintering (typically when mean temperature drops below 13°C), individuals accumulate "prewintering degree-days" (m_DDPrewinter) when daily temperature exceeds 15°C. These degree-days represent final metabolic activity and preparation before winter dormancy. Prewintering DD accumulation affects winter mortality: more accumulation suggests warmer autumn conditions and potentially inadequate cold-hardening.
Phase 2: Overwintering (Winter)
After prewintering ends but before March 1st, individuals accumulate "overwintering degree-days" (m_AgeDegrees) when daily temperature exceeds 0°C. This accumulation directly determines winter mortality probability via the linear equation: mortality = slope × winter_DD + constant. Warmer winters cause higher DD accumulation and thus higher mortality, reflecting metabolic costs and energy depletion.
Phase 3: Pre-emergence (Late Winter/Spring)
Starting March 1st, the emergence counter is calculated based on accumulated winter degree-days: counter_required = constant + slope × winter_DD. The negative slope means warmer winters reduce the required waiting time in spring. Each day with temperature ≥ 5°C decrements the counter. When the counter reaches zero, emergence readiness is achieved, winter mortality is assessed (once only), and emergence proceeds if survived.
Nest Aspect Effects
The emergence counter includes a nest aspect delay (GetAspectDelay()) representing microclimate differences. South-facing nests warm earlier in spring and have shorter delays; north-facing nests experience delayed emergence. This implements realistic phenological variation based on nest-site characteristics.
Late-Season Emergence Deadline
If the emergence counter has not reached zero by June 1st, death occurs. This implements the biological reality that extremely late emergence misses the flowering period and is fatal. This rarely occurs with properly parameterised models but provides a fail-safe against unrealistic parameter combinations.
Emergence Day Variation
The emergence counter includes individual variation via m_emergenceday.Geti(), which draws from the discrete probability distribution based on field observations. This creates realistic phenological spread across 10-15 days even when emergence conditions are met simultaneously.
Implementation Details
Phase determination relies on population manager flags (IsEndPreWinter(), IsOverWinterEnd()) that track seasonal transitions. Temperature retrieval uses m_TempToday (set by population manager before agent steps). The complex logic ensures appropriate phase-specific behaviour without explicit state variables for phases.
Biological Rationale
The three-phase model captures key biological processes:
Prewintering DD: Autumn cold-hardening inadequacy increases winter risk
Winter DD: Metabolic activity during dormancy depletes energy reserves
Emergence counter: Combined thermal and temporal cues prevent premature emergence
This complexity is necessary because simple degree-day models cannot capture emergence timing: individuals must avoid emerging during winter warm spells whilst synchronising with spring flowering. The counter mechanism implements this requirement.
Difference from Formal Model
The emergence threshold temperature was calibrated from 12°C to 5°C to match field emergence timing. The lower threshold allows earlier spring counter accumulation, improving synchronisation with flowering. Winter mortality equation parameters (slope, constant) were adopted directly from Sgolastra et al. (2011) without calibration.
Sensitivity
VERY HIGH - Emergence timing is critically sensitive to threshold temperatures and counter equation parameters. Small changes can shift emergence by 1-2 weeks, with major consequences for reproductive success. Winter mortality is moderately sensitive to the mortality equation parameters and highly sensitive to winter temperature regimes. These sensitivities make this stage a key determinant of population dynamics under climate change scenarios.
Uncertainty
HIGH - The multi-phase model involves numerous parameters (thresholds: 15°C, 0°C, 5°C; equation coefficients; aspect delays) with limited field validation. The counter mechanism is empirically calibrated but the biological mechanisms it represents (photoperiod? cumulative chilling? phenological integration?) are not explicitly modelled. Winter mortality relationships from O. lignaria may not perfectly transfer to O. bicornis.
See also
cfg_OsmiaInCocoonPrewinteringTempThreshold for prewintering threshold (15°C)
cfg_OsmiaInCocoonOverwinteringTempThreshold for overwintering threshold (0°C)
cfg_OsmiaInCocoonEmergenceTempThreshold for emergence counter threshold (5°C, calibrated from 12°C)
cfg_OsmiaInCocoonEmergCountConst for emergence counter equation constant (35.4819)
cfg_OsmiaInCocoonEmergCountSlope for emergence counter equation slope (-0.0147)
WinterMortality() for mortality calculation
Osmia_Nest::GetAspectDelay() for aspect-based phenological variation
This is/must be called each day. If there has been a sudden drop in temperature and the mean temp is below 13 degrees then prewintering is assumed to end and wintering (hibernation) is assumed to start. This is recorded by the population manager in Osmia_Population_Manager::DoLast
Reimplemented from Osmia_Pupa.
Reimplemented in Osmia_Female.
Definition at line 2706 of file Osmia_dox.cpp.
References Osmia_Base::m_Age, Osmia_Egg::m_AgeDegrees, m_DDPrewinter, m_emergencecounter, Osmia_Base::m_emergenceday, Osmia_Base::m_OsmiaInCocoonEmergCountConst, Osmia_Base::m_OsmiaInCocoonEmergCountSlope, Osmia_Base::m_OsmiaInCocoonEmergenceTempThreshold, Osmia_Base::m_OsmiaInCocoonOverwinteringTempThreshold, Osmia_Base::m_OsmiaInCocoonPrewinteringTempThreshold, Osmia_Base::m_OurNest, Osmia_Base::m_OurPopulationManager, Osmia_Base::m_TempToday, toOsmias_Develop, toOsmias_Die, toOsmias_NextStage, and WinterMortality().
Referenced by Step().
st_Emerge()
TTypeOfOsmiaState Osmia_InCocoon::st_Emerge (void) protected virtual
Transition state - emerge from cocoon as active adult.
Execute spring emergence, creating active adult female or removing male.
Returns
Next state (st_Die as InCocoon object deleted)
Spring emergence sequence:
Signal population manager to create Osmia_Female object
Transfer attributes:
Adult mass (determines size and fecundity)
Natal nest location (becomes dispersal origin)
Age (for lifespan tracking)
Any carried-over attributes
Population manager handles nest cleanup (remove from nest cell list)
Delete InCocoon object
New Osmia_Female begins active adult life cycle
Biological Transition
Adult bites through cocoon and cell partition, crawls out of nest, orients to environment, and begins pre-nesting maturation period. In model, this is represented by object class change from InCocoon (dormant, nest-bound) to Female (active, mobile).
Timing Considerations
Emergence typically occurs on warm, sunny days in spring when:
Emergence counter has reached zero (sufficient spring warming accumulated)
Current temperature above threshold (favorable immediate conditions)
Potentially daylight/weather checks (not explicitly modelled)
This ensures emerged adults encounter appropriate conditions for initial flights and resource location.
Implementation Note
The formal model discusses emergence timing but leaves specific trigger details to implementation. This counter-based approach captures observed field patterns: synchronous emergence within 2-3 week period, with timing responding to both winter and spring thermal conditions.
Assesses parasitism outcomes, calculates adult mass from cocoon/provision mass, and creates Osmia_Female object for females. Males are not modelled explicitly and quietly vanish at this stage.
Returns
toOsmias_Emerged (return value not used as object is destroyed)
Biological Context
Spring emergence represents the transition from overwintering pharate adult to active adult. Adults chew through the cocoon and exit the nest to begin reproductive activities. Emergence timing critically determines reproductive success: individuals must synchronise with flowering whilst avoiding late-season emergence that provides insufficient time for nest provisioning.
Sex-Specific Outcomes
Males (m_Sex == false): Not explicitly modelled. Males quietly vanish at emergence, with their presence implicitly assumed for female reproduction. This simplification focuses modelling effort on population dynamics-determining female reproduction.
Females (m_Sex == true): Create Osmia_Female object with body mass calculated from provision mass. Adult female mass determines reproductive potential through mass-fecundity relationships.
Parasitism Outcomes
Parasitised individuals (m_ParasitoidStatus != topara_Unparasitised) die at emergence. The commented code suggests potential future enhancement where parasitised individuals could emerge with reduced mass rather than dying, but current implementation causes death. For nest parasites like Cacoxenus indagator, parasitism typically prevents adult emergence entirely.
Mass Calculation
Adult female mass is calculated from cocoon/provision mass via the linear equation: adult_mass = constant + slope × provision_mass
The provision mass (m_Mass inherited through development) represents the pollen-nectar mass accumulated by the mother and consumed by the larva. This mass determines cocoon mass, which determines adult mass through the conversion equation. The 25% conversion efficiency (slope = 0.25) reflects metabolic costs and structural losses during complete metamorphosis.
Age Reset
Adult age resets to zero at emergence (sO.age = 0), with subsequent counting tracking adult lifespan rather than developmental age. This reset is biologically meaningful: adult longevity begins at emergence, not at oviposition.
Nest Disassociation
Newly emerged females have no nest association (sO.nest = nullptr). They will conduct prenesting behaviour, dispersal, and nest-site selection before establishing their own nest. This reflects the biological reality that O. bicornis females do not reuse their natal nest.
Model Outputs
Records overwintering duration under OSMIATESTING for validation. Given the complexity of overwintering and the calibrations applied to emergence parameters, comparing simulated durations and emergence timing with field observations is important for model credibility.
Implementation Notes
The commented parasitoid code (lines 767-776) suggests planned enhancement for parasitoid population dynamics. Currently parasitoid effects are limited to binary outcomes (emerge or die) based on parasitism status assigned during nest provisioning. Future versions might model parasitoid populations explicitly and calculate mass reduction for emerged parasitised individuals.
See also
Osmia_Female constructor and Init() for female initialization
cfg_OsmiaFemaleMassFromProvMassSlope for conversion slope (0.25)
cfg_OsmiaFemaleMassFromProvMassConst for conversion constant (4.0 mg)
struct_Osmia for state transfer data structure
If this is a male (sex == false) we quietly let it vanish, since we do not model adult males.
If parasitised then first determine the result of the parasitism
/switch (m_ParasitoidStatus) { case TTypeOfOsmiaParasitoids::topara_Bombylid: m_OurNest->KillAllSubsequentCells(this); m_OurParasitoidPopulationManager->AddParasitoid(TTypeOfOsmiaParasitoids::topara_Bombylid, m_Location_x, m_Location_y); break; case TTypeOfOsmiaParasitoids::topara_Cleptoparasite: m_OurParasitoidPopulationManager->AddParasitoid(TTypeOfOsmiaParasitoids::topara_Cleptoparasite, m_Location_x, m_Location_y); break; }
Creates a new Osmia adult object and passes the data from the pupa to it, then signals young object removal.
Osmia_Female mass can be calculated from the Osmia_InCocoon mass as follows:
bee_mass = 4.0 + cocoon_mass * 0.8
The relation between cocoon mass and provisioning mass is: CfgLinear Cfg_OsmiaCocoonMassFromProvMass_Female = [1/3.247, 0] cocoon_mass = provision *1/3.247 So we can calculate the combination of the two linear relationships to get female mass from provision mass by: mass = 0.246381*provision_mass + 4.0
Reimplemented from Osmia_Pupa.
Definition at line 2813 of file Osmia_dox.cpp.
References struct_Osmia::age, struct_Osmia::L, Osmia_Base::m_Age, Osmia_Base::m_Mass, Osmia_Base::m_OsmiaFemaleMassFromProvMassConst, Osmia_Base::m_OsmiaFemaleMassFromProvMassSlope, Osmia_Base::m_OurNest, Osmia_Base::m_OurPopulationManager, Osmia_Base::m_ParasitoidStatus, Osmia_Egg::m_Sex, Osmia_Egg::m_StageAge, struct_Osmia::mass, struct_Osmia::nest, struct_Osmia::OPM, struct_Osmia::parasitised, struct_Osmia::sex, to_OsmiaFemale, toOsmias_Die, toOsmias_Emerged, topara_Unparasitised, struct_Osmia::x, and struct_Osmia::y.
Referenced by Step().
Step()
void Osmia_InCocoon::Step (void) virtual
Main step function for overwintering adults.
Execute daily time step for overwintering adult.
Each day:
Call st_Develop to update DD accumulation and counters
Check emergence conditions (counter ≤ 0 and T > threshold)
Apply winter mortality test based on accumulated prewinter DD
Transition to emergence or continue overwintering
Implements state machine controlling overwintering behaviour. InCocoon adults call st_Develop() to progress through prewintering, overwintering, and pre-emergence phases until spring emergence conditions are met.
State Machine Logic
toOsmias_InitialState: Entry point, transitions immediately to Develop
toOsmias_Develop: Progresses through overwintering phases, accumulates degree-days/emergence counter
toOsmias_NextStage: Triggers spring emergence via st_Emerge(), creating active adult
toOsmias_Die: Executes death from winter mortality or emergence failure
Biological Context
Overwintering represents the longest single life stage (6-8 months typically), during which individuals are immobile within cocoons experiencing temperature-dependent mortality and preparing for spring emergence. The multi-phase developmental model ensures biologically realistic phenology, preventing emergence during winter warm spells whilst synchronising emergence with spring flowering.
Mortality
Unlike earlier stages with constant daily mortality, overwintering adults face temperature-dependent winter mortality assessed once at emergence. The linear mortality equation relates accumulated winter degree-days to mortality probability, implementing the biological reality that warmer winters increase metabolic costs and energy depletion.
See also
st_Develop() for complex phase-specific logic
st_Emerge() for spring emergence and adult creation
Osmia adult in cocoon behaviour is simple. It calls develop until the adult in cocoon emerges or dies.
Reimplemented from Osmia_Pupa.
Reimplemented in Osmia_Female.
Definition at line 2587 of file Osmia_dox.cpp.
References Osmia_Base::m_CurrentOState, st_Develop(), Osmia_Base::st_Dying(), st_Emerge(), toOsmias_Develop, toOsmias_Die, toOsmias_InitialState, and toOsmias_NextStage.
WinterMortality()
bool Osmia_InCocoon::WinterMortality () protected
Calculate overwintering mortality probability from prewinter thermal conditions.
Calculate winter mortality probability and determine survival.
Returns
true if dies, false if survives
Implements Sgolastra et al. (2011) linear relationship: mortality_probability = 0.05 × m_DDPrewinter - 4.63
Then tests this probability against uniform random number to determine fate.
Example calculations:
m_DDPrewinter = 30 DD → mortality = 0.05×30 - 4.63 = -3.13 → 0.0 (clamped) → 0% death
m_DDPrewinter = 60 DD → mortality = 0.05×60 - 4.63 = -1.63 → 0.0 (clamped) → 0% death
m_DDPrewinter = 93 DD → mortality = 0.05×93 - 4.63 = 0.02 → 2% death
m_DDPrewinter = 100 DD → mortality = 0.05×100 - 4.63 = 0.37 → 37% death
m_DDPrewinter = 130 DD → mortality = 0.05×130 - 4.63 = 1.87 → 1.0 (clamped) → 100% death
Biological Interpretation
The equation captures lipid depletion during warm prewintering. Each degree-day above 15°C represents time at elevated metabolism, burning fat reserves needed for winter survival. The negative intercept (-4.63) means zero mortality at low DD accumulation (cool autumns provide ideal prewintering conditions). Mortality rises linearly with warm autumn conditions.
Difference from Formal Model
EXACT MATCH - Equation coefficients implemented precisely as specified in formal model (const = -4.63, slope = 0.05). Based directly on Sgolastra et al. (2011) empirical data for O. lignaria males, applied to both sexes of O. bicornis in absence of sex-specific data.
Uncertainty
MEDIUM - Cross-species application (O. lignaria → O. bicornis) introduces uncertainty. Male-to-female extrapolation also uncertain (females may differ in lipid reserves and metabolic rates). However, underlying mechanism (fat depletion at warm temperatures) is well-established and should be qualitatively similar across related species and sexes.
Implementation Details
Probability clamped to [0, 1] range (equation can produce values outside this range)
Mortality test occurs once per overwintering period (not daily like developmental stages)
Timing of test determines whether early-season or late-season conditions dominate
Current implementation likely tests in spring (precise timing depends on Step logic)
Valid DD Range and Interpretation
0-90 DD: Ideal to good prewintering (mortality 0-10%)
90-110 DD: Moderate stress (mortality 10-40%)
110-130 DD: Poor conditions (mortality 40-80%)
>130 DD: Catastrophic (mortality >80%)
Central European autumns typically produce 30-80 DD, giving 0-20% mortality under normal conditions. Climate warming could increase DD accumulation, raising population-level mortality risk.
Implements linear relationship between accumulated prewintering degree-days and mortality probability. Called once at emergence readiness to determine overwintering survival.
Returns
true if individual dies, false if survives
Biological Rationale
Winter mortality in solitary bees results from multiple interacting factors: cold stress, energy depletion from elevated metabolism during warm periods, pathogen susceptibility, and inadequate cold-hardening. The linear model captures the net effect: warmer autumns/winters (more prewintering DD accumulation) increase mortality because pharate adults experience elevated metabolism without feeding opportunities, depleting energy reserves needed for emergence and reproduction.
Mortality Equation
mortality_probability = slope × prewintering_DD + constant Where:
slope = 0.05 (5% mortality increase per DD)
constant = -4.63 (baseline negative, requiring ~93 DD before appreciable mortality)
prewintering_DD = m_DDPrewinter (accumulated during autumn above 15°C threshold)
The equation predicts approximately 0% mortality at 93 DD, 10% at 293 DD, and 20% at 493 DD. This reflects the biological reality that moderate thermal accumulation (cool autumn, cold winter) poses minimal risk, whilst substantial accumulation (warm autumn, mild winter) causes significant mortality from energy depletion.
Empirical Basis
Equation derived from Sgolastra et al. (2011) study with Osmia lignaria, a closely related North American species. Transfer to O. bicornis assumes similar physiological responses to winter thermal conditions, reasonable given ecological similarities (both are early-season, cavity-nesting solitary bees).
Implementation Notes
Mortality is assessed probabilistically: a random number (0-100) compared against predicted mortality percentage determines outcome. This one-time assessment occurs when emergence readiness is achieved (emergence counter reaches zero). Individuals passing this test successfully emerge; those failing die within the cocoon.
Counterintuitive Relationship
The positive relationship between winter thermal accumulation and mortality seems counterintuitive (warmer = worse), but reflects genuine biology: pharate adults cannot feed whilst in cocoons, so warmer conditions causing elevated metabolism without energy input deplete reserves. Very cold winters (minimal DD) cause minimal mortality because metabolism remains suppressed. This relationship has important implications for climate change impacts.
Difference from Formal Model
EXACT MATCH. No calibration applied; equation adopted directly from Sgolastra et al. (2011).
Sensitivity
HIGH - Winter mortality is a major demographic bottleneck. The slope parameter (0.05) determines how strongly winter thermal conditions affect survival. Under climate change scenarios causing warmer winters, this relationship could substantially reduce population viability even without changes to summer conditions.
Uncertainty
MEDIUM - Transfer from O. lignaria introduces uncertainty. O. bicornis may have different cold-hardening capabilities or metabolic responses. The linear relationship is a simplification; true mortality likely involves threshold effects, non-linearities, and interactions with other stressors (pathogens, cocoon condition). However, the general pattern (warmer winters increase mortality) is well-supported biologically.
See also
cfg_OsmiaInCocoonWinterMortSlope for slope parameter (0.05)
cfg_OsmiaInCocoonWinterMortConst for constant parameter (-4.63)
Sgolastra et al. (2011) Journal of Apicultural Research 50: 149-158
st_Develop() for prewintering DD accumulation logic
Osmia in cocoon is immobile and overwinters in the nest so only call this once at the end of overwintering Overwintering mortality depends on pre-wintering degree-days accumulation, DDPrewinter with a baseline temperature T0 = 15 C degrees, and only for days when Tavg – T0 >= 0
Definition at line 2939 of file Osmia_dox.cpp.
References m_DDPrewinter, Osmia_Base::m_OsmiaInCocoonWinterMortConst, and Osmia_Base::m_OsmiaInCocoonWinterMortSlope.
Referenced by st_Develop().
Member Data Documentation
m_DDPrewinter
double Osmia_InCocoon::m_DDPrewinter protected
Accumulated degree-days during prewintering period (above 15°C baseline).
Accumulates from eclosion through autumn. Only temperatures above 15°C contribute: DD_prewinter += (T_daily - 15) when T > 15°C
Used in overwintering mortality calculation. High values (prolonged warm autumn) increase mortality risk via fat depletion. Reset to zero at eclosion for new adults.
Biological Basis
At temperatures above 15°C, prepupal/adult metabolism remains elevated, burning lipid reserves that are needed for winter survival. Bosch et al. (2008) documented weight loss rates of 0.2-0.4 mg/day during warm prewintering, with corresponding survival reductions.
Difference from Formal Model
EXACT MATCH - Implementation follows formal model specification precisely. The 15°C baseline comes directly from Sgolastra et al. (2011) methodology.
Valid Range
[0, ~150] degree-days. Values >100 DD indicate poor overwintering conditions (prolonged warmth). Typical central European autumn might accumulate 30-60 DD, giving mortality around 0.2-0.4 (20-40% death probability).
Definition at line 116 of file Osmia_enh_PART3_Final.h.
Referenced by GetDDPreWinter(), Osmia_InCocoon(), ReInit(), st_Develop(), and WinterMortality().
m_emergencecounter
int Osmia_InCocoon::m_emergencecounter protected
Countdown to spring emergence (decrements with warm days).
Initialized at eclosion using equation: counter = 35.48 - 0.0147 × initial_DD Each day above emergence threshold (5°C) decrements counter by accumulated DD that day. When counter reaches zero (or negative), adult emerges from nest.
Biological Interpretation
The counter represents integrated thermal accumulation needed for emergence readiness. After diapause completion (chilling requirement met), adults still need specific amount of spring warming before emergence is triggered. Counter mechanism ensures emergence synchrony with appropriate spring phenology (flower availability, favorable weather).
Empirical Basis
Equation calibrated from field emergence observations showing relationship between winter/spring thermal patterns and emergence dates. Lower initial DD (cool conditions) requires more spring warming (higher counter start), whilst higher initial DD needs less spring warming.
Implementation Note
Counter can become negative if warm spring arrives rapidly - this is acceptable as it simply means emergence threshold was exceeded quickly. Once counter ≤ 0, emergence occurs on next favorable day (temperature above emergence threshold).
Definition at line 91 of file Osmia_enh_PART3_Final.h.
Referenced by Osmia_InCocoon(), ReInit(), and st_Develop().
m_OverwinteringTempThreshold
double Osmia_InCocoon::m_OverwinteringTempThreshold = 0.0 static protected
Static temperature threshold for overwintering phase (°C).
Default: 0.0°C. Defines baseline for diapause proper. Temperatures near/below this threshold represent true winter conditions where metabolism is minimized and lipid conservation is maximal.
Usage
Not used for DD accumulation (unlike egg/larva/pupa thresholds) but serves as conceptual boundary between active prewintering (>15°C), transitional conditions (0-15°C), and true diapause (<0°C approximately).
Definition at line 315 of file Osmia_enh_PART3_Final.h.
Referenced by cfg_OsmiaOverwinterDegreeDaysInitialSimu(), and SetOverwinteringTempThreshold().
The documentation for this class was generated from the following files:
src/Osmia_enh_PART3_Final.h
src/Osmia_dox.cpp
src/Osmia_Population_Manager_dox.cpp