Osmia bicornis Population Model: Osmia_Prepupa Class Reference
Osmia_Prepupa Class Reference
Prepupal diapause stage in cocoon.
#include <Osmia_enh_PART2_LifeStages.h>
Public Member Functions
Osmia_Prepupa (struct_Osmia *data)
Constructor transferring from larva to prepupa.
virtual void ReInit (struct_Osmia *data)
Reinitialize prepupa from object pool.
virtual ~Osmia_Prepupa ()
Destructor.
virtual void Step (void)
Main step function.
Public Member Functions inherited from Osmia_Larva
Osmia_Larva (struct_Osmia *data)
Constructor for new larva (created during egg hatching).
virtual ~Osmia_Larva ()
Destructor.
Public Member Functions inherited from Osmia_Egg
Osmia_Egg (struct_Osmia *data)
Constructor for new egg object.
virtual ~Osmia_Egg ()
Destructor.
double GetAgeDegrees ()
Get accumulated degree-days.
void SetAgeDegrees (unsigned a_agedegrees)
Set accumulated degree-days (used during object reinitialization).
Public Member Functions inherited from Osmia_Base
Osmia_Base (struct_Osmia *data)
Constructor creating new Osmia_Base individual.
void ReInit (struct_Osmia *data)
Reinitialize object from object pool.
virtual ~Osmia_Base ()
Virtual destructor ensuring proper cleanup in derived classes.
virtual void st_Dying (void)
Behavioural state for death - cleanup and removal.
virtual void BeginStep (void)
First phase of daily timestep.
virtual void EndStep (void)
Final phase of daily timestep.
int GetAge ()
Get individual's age in days.
void SetAge (int a_age)
Set individual's age in days.
double GetMass ()
Get individual's mass (mg) - interpretation depends on life stage.
void SetMass (double a_mass)
Set individual's mass (mg).
void SetParasitised (TTypeOfOsmiaParasitoids a_status)
Set parasitism status.
TTypeOfOsmiaParasitoids GetParasitised (void)
Get parasitism status.
Osmia_Nest * GetNest ()
Get pointer to nest containing or being provisioned by this individual.
Protected Member Functions
virtual TTypeOfOsmiaState st_Develop (void)
Development state - time-based progression toward pupation.
virtual TTypeOfOsmiaState st_Pupate (void)
Transition state - metamorphose from prepupa to pupa.
virtual bool DailyMortality ()
Daily mortality test for prepupae.
Protected Member Functions inherited from Osmia_Larva
virtual TTypeOfOsmiaState st_Prepupate (void)
Transition state - metamorphose from larva to prepupa.
Protected Member Functions inherited from Osmia_Egg
virtual TTypeOfOsmiaState st_Hatch (void)
Transition state - metamorphose from egg to larva.
Protected Attributes
double m_myOsmiaPrepupaDevelTotalDays
Individual-specific prepupal development duration (days).
Protected Attributes inherited from Osmia_Egg
double m_AgeDegrees = 0.0
Accumulated degree-days toward hatching threshold.
bool m_Sex
Sex of individual (true = female = fertilised egg).
int m_StageAge
Age in days when current life stage was entered.
double m_egg_pest_mortality
Cumulative pesticide mortality probability for this egg.
Protected Attributes inherited from Osmia_Base
TTypeOfOsmiaState m_CurrentOState
Current behavioural state governing agent decisions.
int m_Age
Chronological age in days since egg laying.
Osmia_Population_Manager * m_OurPopulationManager
Pointer to the Osmia population manager instance.
TTypeOfOsmiaParasitoids m_ParasitoidStatus
Records parasitism status of this individual.
Osmia_Nest * m_OurNest
Pointer to nest containing this individual.
double m_Mass
Mass of individual or provision (mg) - interpretation varies by life stage.
int m_foragehours
Hours available for foraging today (decremented as foraging proceeds).
Additional Inherited Members
Static Public Member Functions inherited from Osmia_Base
static void SetParameterValues ()
Populate all static parameters from configuration file.
static void SetTemp (double a_temperature)
Set current daily temperature for all individuals.
static void SetParasitoidManager (OsmiaParasitoid_Population_Manager *a_popman)
Set parasitoid population manager pointer.
Static Protected Attributes inherited from Osmia_Base
static OsmiaParasitoid_Population_Manager * m_OurParasitoidPopulationManager = NULL
Static pointer to parasitoid population manager (if using mechanistic parasitoid model).
static double m_TempToday = -9999
Mean daily temperature (°C) for current timestep.
static int m_TempTodayInt = -9999
Rounded integer temperature for array indexing.
static double m_DailyDevelopmentMortEggs = 0
Daily mortality probability for eggs (probability per day).
static double m_DailyDevelopmentMortLarvae = 0
Daily mortality probability for larvae (probability per day).
static double m_DailyDevelopmentMortPrepupae = 0
Daily mortality probability for prepupae (probability per day).
static double m_DailyDevelopmentMortPupae = 0
Daily mortality probability for pupae (probability per day).
static double m_OsmiaEggDevelTotalDD = 0
Total degree-days required for egg development to hatching.
static double m_OsmiaEggDevelThreshold = 0
Lower developmental threshold temperature for eggs (°C).
static double m_OsmiaLarvaDevelTotalDD = 0
Total degree-days required for larval development to prepupal stage.
static double m_OsmiaLarvaDevelThreshold = 0
Lower developmental threshold temperature for larvae (°C).
static double m_OsmiaPupaDevelTotalDD = 0
Total degree-days required for pupal development to adult eclosion.
static double m_OsmiaPupaDevelThreshold = 0
Lower developmental threshold temperature for pupae (°C).
static double m_OsmiaPrepupalDevelTotalDays = 0
Total days for prepupal development at optimal temperature.
static double m_OsmiaPrepupalDevelTotalDays10pct = 0
Pre-computed 10% of prepupal development time.
static double m_OsmiaInCocoonOverwinteringTempThreshold = 0
Temperature threshold (°C) for accumulating overwintering degree-days.
static double m_OsmiaInCocoonEmergenceTempThreshold = 0
Temperature threshold (°C) for post-diapause emergence counter.
static double m_OsmiaInCocoonPrewinteringTempThreshold = 0
Temperature threshold (°C) for accumulating prewintering degree-days.
static double m_OsmiaInCocoonWinterMortConst = 0.0
Intercept for overwintering mortality equation.
static double m_OsmiaInCocoonWinterMortSlope = 0.0
Slope for overwintering mortality equation.
static double m_OsmiaInCocoonEmergCountConst = 0.0
Intercept for emergence counter equation.
static double m_OsmiaInCocoonEmergCountSlope = 0.0
Slope for emergence counter equation.
static double m_OsmiaFemaleMassFromProvMassConst = 0.0
Intercept for calculating female mass from provision mass.
static double m_OsmiaFemaleMassFromProvMassSlope = 0.0
Slope for calculating female mass from provision mass.
static double m_MaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for male nest cells (mg).
static double m_MaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for male nest cells (mg).
static double m_FemaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxMass = 0.0
Maximum female adult mass (mg) - sets upper bound for provision mass calculations.
static double m_FemaleMinMass = 0.0
Minimum female adult mass (mg) - sets lower bound for provision mass calculations.
static double m_MaleMaxMass = 0.0
Maximum male adult mass (mg) - males are smaller than females.
static double m_PollenScoreToMg = 0.0
Conversion factor from pollen availability score to provisioned mass (mg pollen per day).
static double m_DensityDependentPollenRemovalConst = 0.0
Parameter linking pollen depletion to Osmia population density.
static double m_MinimumCellConstructionTime = 0.0
Minimum time (days) required to construct and provision one nest cell.
static double m_MaximumCellConstructionTime = 0.0
Maximum time (days) required to construct and provision one nest cell.
static int m_TotalNestsPossible = 0
Maximum number of nests a female can complete in her lifetime.
static double m_BombylidProbability = 0.0
Baseline probability of bombyliid fly parasitism per open nest cell.
static double m_ParasitismProbToTimeCellOpen = 0.0
Conversion factor relating cell open time (days) to parasitism probability.
static vector< double > m_ParasitoidAttackChance = {}
Per-capita parasitoid attack probabilities for mechanistic parasitoid model.
static double m_OsmiaFemaleR50distance = 0.0
Typical homing distance - distance at which 50% of females cannot return to nest (m).
static double m_OsmiaFemaleR90distance = 0.0
Maximum homing distance - distance at which 90% of females cannot return (m).
static int m_OsmiaFemalePrenesting = 0
Duration of prenesting period after emergence (days).
static int m_OsmiaFemaleLifespan = 0
Maximum adult female lifespan (days).
static probability_distribution m_generalmovementdistances = probability_distribution(cfg_OsmiaGeneralMovementProbType.value(), cfg_OsmiaGenerallMovementProbArgs.value())
Probability distribution for foraging and nest-searching movements.
static probability_distribution m_dispersalmovementdistances = probability_distribution(cfg_OsmiaDispersalMovementProbType.value(), cfg_OsmiaDispersalMovementProbArgs.value())
Probability distribution for dispersal movements (longer than foraging movements).
static probability_distribution m_eggspernestdistribution = probability_distribution(cfg_OsmiaEggsPerNestProbType.value(), cfg_OsmiaEggsPerNestProbArgs.value())
Probability distribution for planned eggs per nest.
static probability_distribution m_exp_ZeroToOne = probability_distribution("BETA", "1.0, 5.0")
Exponential-like probability distribution over range [0,1].
static double m_CocoonToProvisionMass = 0.0
Mass conversion ratio from cocoon mass to provision mass required.
static double m_ProvisionToCocoonMass = 0.0
Mass conversion ratio from provision mass to resulting cocoon mass.
static double m_TotalProvisioningMassLoss = 0.0
Total provision mass loss from first to last egg in a nest (mg).
static double m_TotalProvisioningMassLossRange = 0.0
Stochastic range around total provisioning mass loss (mg).
static double m_TotalProvisioningMassLossRangeX2 = 0.0
Pre-computed double of mass loss range for efficiency.
static bool m_UsingMechanisticParasitoids = false
Flag selecting parasitism model: true=mechanistic population model, false=simple probabilities.
static double m_OsmiaFemaleBckMort = 0.0
Daily background mortality for adult females outside nest (probability per day).
static int m_OsmiaFemaleMinEggsPerNest = 0
Minimum eggs planned per nest (sets lower bound for egg planning distribution).
static int m_OsmiaFindNestAttemptNo = 0
Number of attempts allowed for finding suitable nest location before giving up.
static int m_OsmiaFemaleMaxEggsPerNest = 0
Maximum eggs planned per nest (sets upper bound for egg planning distribution).
static probability_distribution m_emergenceday = probability_distribution(cfg_OsmiaEmergenceProbType.value(), cfg_OsmiaEmergenceProbArgs.value())
Probability distribution for day of emergence relative to population mean.
Detailed Description
Prepupal diapause stage in cocoon.
Osmia_Prepupa represents the prepupal dormancy period following cocoon spinning. This stage uses time-based rather than degree-day-based development, with non-linear temperature relationships. Prepupae are relatively invulnerable, having lowest mortality of any stage.
Biological Foundation
The prepupal stage is characterized by arrested development (diapause) lasting 1-3 months depending on temperature and photoperiod cues. O. bicornis prepupae show optimal development at intermediate temperatures (~22°C) with both lower and higher temperatures extending development time. This non-linear response distinguishes prepupae from other stages' monotonic temperature relationships.
Development Model
MAJOR DIFFERENCE FROM FORMAL MODEL: Formal model specified quadratic temperature-development function with 24.3-day optimum at 22°C. Implementation uses simpler time-based approach: base duration 45 days with individual variation (±10%), plus temperature threshold effects rather than continuous function. This pragmatic simplification reflects limited data for robust parameterization of non-linear relationship.
Rationale for Simplified Model
Quadratic functions require precise parameterization of both optimal temperature and curvature. Available data (Radmacher & Strohm 2011, Giejdasz & Fliszkiewicz 2016) show scatter making curve fitting uncertain. Time-based approach with thresholds provides more stable model behaviour whilst capturing key biology: prepupae take several weeks and respond to temperature extremes.
Mortality
Lowest of all stages (0.003 daily probability). Well-supported empirically - cocooned prepupae are protected and physiologically inactive, minimizing vulnerability.
Definition at line 332 of file Osmia_enh_PART2_LifeStages.h.
Constructor & Destructor Documentation
Osmia_Prepupa()
Osmia_Prepupa::Osmia_Prepupa (struct_Osmia * data)
Constructor transferring from larva to prepupa.
Constructor for Osmia_Prepupa from initialization data.
Creates a new prepupa agent with individual variation in developmental duration. Unlike eggs and larvae, prepupae use time-based rather than degree-day development.
Parameters
data Pointer to struct_Osmia containing initialization data
Biological Context
The prepupal stage is a non-feeding transitional phase between larval feeding and pupal metamorphosis. Prepupae void gut contents (producing meconium), construct the silk cocoon, and undergo preliminary physiological changes preparing for metamorphosis. This stage shows less consistent temperature-dependent development than earlier stages, likely due to behavioural components (cocoon spinning) and the onset of diapause preparation.
Developmental Model
Uses time-based development (days elapsed) rather than degree-day accumulation. Each individual draws a random developmental duration from a uniform distribution centred on cfg_OsmiaPrepupaDevelTotalDays (45 days) with ±10% variation. This approach acknowledges insufficient data for robust degree-day parameterisation and reflects the complex, possibly non-linear temperature responses during this stage.
Individual Variation
The calculation m_myOsmiaPrepupaDevelTotalDays = mean + (0.2 * mean * uniform_random) - (0.1 * mean) produces uniform variation from 90% to 110% of the mean duration. This represents natural individual variation in cocoon construction rates and physiological preparation timing.
Rationale for Time-Based Approach
The formal model recognised insufficient data for robust degree-day parameterisation of the prepupal stage. Laboratory studies suggest complex, potentially non-linear temperature responses during cocoon construction and preliminary metamorphic changes. The time-based approach provides adequate realism whilst acknowledging these data limitations and biological complexities.
See also
cfg_OsmiaPrepupaDevelTotalDays for mean duration parameter (45 days)
Parameter documentation for discussion of formal model comparison
Definition at line 2060 of file Osmia_dox.cpp.
References Osmia_Egg::m_AgeDegrees, m_myOsmiaPrepupaDevelTotalDays, Osmia_Base::m_OsmiaPrepupalDevelTotalDays, Osmia_Base::m_OsmiaPrepupalDevelTotalDays10pct, Osmia_Larva::Osmia_Larva(), and ReInit().
Referenced by Osmia_Pupa::Osmia_Pupa().
~Osmia_Prepupa()
Osmia_Prepupa::~Osmia_Prepupa (void) virtual
Destructor.
Destructor for Osmia_Prepupa.
Empty destructor as cleanup is handled by base classes. Prepupae transition to pupae upon completing development.
Definition at line 2020 of file Osmia_dox.cpp.
Member Function Documentation
DailyMortality()
virtual bool Osmia_Prepupa::DailyMortality () inline protected virtual
Daily mortality test for prepupae.
Returns
true if dies, false if survives
Uses m_DailyDevelopmentMortPrepupae (0.003) - higher than egg/larva but still very low. Cocooned prepupae are well-protected.
Reimplemented from Osmia_Larva.
Reimplemented in Osmia_Pupa.
Definition at line 384 of file Osmia_enh_PART2_LifeStages.h.
References Osmia_Base::m_DailyDevelopmentMortPrepupae.
Referenced by st_Develop().
ReInit()
void Osmia_Prepupa::ReInit (struct_Osmia * data) virtual
Reinitialize prepupa from object pool.
Reinitialize an existing Osmia_Prepupa object with new data.
Chains to Osmia_Larva::ReInit() to inherit larva/egg state initialization.
Parameters
data Pointer to struct_Osmia containing new initialization data
Implementation Notes
Prepupae inherit the state variable structure from larvae but use fundamentally different developmental mechanisms (time-based rather than degree-day), reflecting unique prepupal biology.
Reimplemented from Osmia_Larva.
Reimplemented in Osmia_Female, Osmia_InCocoon, and Osmia_Pupa.
Definition at line 2010 of file Osmia_dox.cpp.
References Osmia_Larva::ReInit().
Referenced by Osmia_Prepupa(), and Osmia_Pupa::ReInit().
st_Develop()
TTypeOfOsmiaState Osmia_Prepupa::st_Develop (void) protected virtual
Development state - time-based progression toward pupation.
Execute daily prepupal development and mortality.
Returns
Next state (st_Pupate when duration complete, st_Develop to continue, or st_Die)
Different development logic from egg/larva:
Check if prepupal age >= m_myOsmiaPrepupaDevelTotalDays
Temperature affects this duration via threshold checks (not continuous function)
Apply daily mortality test (very low)
Transition to pupa when time threshold reached
Temperature Effects
Rather than quadratic function, implementation uses temperature thresholds:
Above prewintering threshold (15°C): development proceeds
Below threshold: development suspended This creates appropriate seasonal timing without complex non-linear function.
Individual Variation
Each prepupa gets individual m_myOsmiaPrepupaDevelTotalDays drawn from uniform distribution (base ± 10%), creating realistic spread in prepupal durations even under identical temperatures.
Uses time-based development counter rather than degree-day accumulation. Increments age and a separate development counter until the individual-specific duration is reached.
Returns
Next state: toOsmias_Die if mortality occurs, toOsmias_NextStage if development duration is reached, toOsmias_Develop to continue development
Biological Rationale
The prepupal stage involves cocoon construction, waste elimination, and preliminary physiological changes that do not follow simple thermal accumulation patterns. The time-based approach acknowledges this complexity whilst providing adequate realism for population dynamics. The elevated mortality rate (0.3% daily, compared to 0.14% for eggs/larvae) reflects the physiological demands of this transitional stage.
Implementation Details
The population manager provides a daily "developmental days" increment via GetPrePupalDevelDays(), which typically returns 1.0 but could implement temperature-modification if desired. The variable m_AgeDegrees (misnomer, actually counts days) increments with this value. When this counter exceeds the individual's m_myOsmiaPrepupaDevelTotalDays, pupation occurs.
Note on Variable Naming
The variable m_AgeDegrees is a misnomer inherited from the degree-day based stages. For prepupae, it actually counts days rather than degree-days. The double-increment (m_AgeDegrees++) in the comparison line appears to be a coding artefact but increments the counter appropriately.
Difference from Formal Model
MAJOR DIFFERENCE: Formal model attempted degree-day based development but acknowledged insufficient data. Implementation uses time-based approach with individual variation, representing a pragmatic solution acknowledging data limitations whilst maintaining biological plausibility. The mean duration increased from 24.292 days (initial attempt) to 45 days (current implementation).
Sensitivity
MEDIUM - The prepupal stage duration and elevated mortality make this a significant population bottleneck. However, the time-based approach reduces sensitivity to temperature variation compared to degree-day stages. Individual variation (±10%) introduces realistic phenological spread.
Uncertainty
HIGH - Very limited empirical data on prepupal development, particularly regarding temperature responses. The time-based model is a simplification that may not capture important thermal effects, but available data are insufficient for more complex parameterisation.
See also
DailyMortality() for mortality calculation (0.3% daily)
cfg_OsmiaPrepupaDevelTotalDays for mean duration parameter (45 days)
Constructor for individual variation implementation
Development occurs if the prepupa does not die of non-specified causes. Temperature drives the basic development towards a target m_myOsmiaPrepupaDevelTotalDays. This has individual variation built in around a mean value.
Reimplemented from Osmia_Larva.
Reimplemented in Osmia_Female, Osmia_InCocoon, and Osmia_Pupa.
Definition at line 2164 of file Osmia_dox.cpp.
References DailyMortality(), Osmia_Base::m_Age, Osmia_Egg::m_AgeDegrees, m_myOsmiaPrepupaDevelTotalDays, Osmia_Base::m_OurPopulationManager, toOsmias_Develop, toOsmias_Die, and toOsmias_NextStage.
Referenced by Step().
st_Pupate()
TTypeOfOsmiaState Osmia_Prepupa::st_Pupate (void) protected virtual
Transition state - metamorphose from prepupa to pupa.
Execute pupation, creating pupa and removing prepupa.
Returns
Next state (st_Die as prepupa deleted)
Standard metamorphosis: create Osmia_Pupa, transfer attributes, update nest, delete prepupa. Biologically represents transition from dormant prepupa to active metamorphic pupa.
Creates a new Osmia_Pupa object inheriting all state from the prepupa, then removes the prepupa object. Marks the transition from the non-feeding preparatory stage to metamorphosis.
Returns
toOsmias_Emerged (return value not used as object is destroyed)
Biological Context
Pupation initiates complete metamorphosis within the sealed cocoon. The prepupa has completed cocoon construction and waste elimination; the pupa will undergo histolysis of larval tissues and histogenesis of adult structures. This is the most profound physiological transformation in the life cycle, with elevated mortality risk (0.3% daily) reflecting the complexity of metamorphosis.
State Transfer
All state transfers to the pupa: body mass (determines adult size), sex (determines adult structures to develop), parasitism status, nest association, and age. The pupa will use degree-day based development but with highly calibrated parameters (LDT = 1.1°C, SET = 570 DD) reflecting the critical importance of appropriate overwintering timing.
Model Outputs
Records prepupal duration under OSMIATESTING for validation against field observations. Prepupal duration is variable and poorly documented in the field, making this a useful model output for comparison with any available data.
See also
Osmia_Pupa constructor for pupa initialization
struct_Osmia for state transfer data structure
Determines sex, and creates a new Osmia pupa object and passes the data from the prepupa to it, then signals young object removal.
Definition at line 2206 of file Osmia_dox.cpp.
References struct_Osmia::age, struct_Osmia::L, Osmia_Base::m_Age, Osmia_Base::m_Mass, Osmia_Base::m_OurNest, Osmia_Base::m_OurPopulationManager, Osmia_Base::m_ParasitoidStatus, Osmia_Egg::m_Sex, Osmia_Egg::m_StageAge, struct_Osmia::mass, struct_Osmia::nest, struct_Osmia::OPM, struct_Osmia::parasitised, struct_Osmia::sex, to_OsmiaPupa, toOsmias_Emerged, struct_Osmia::x, and struct_Osmia::y.
Referenced by Step().
Step()
void Osmia_Prepupa::Step (void) virtual
Main step function.
Execute daily time step for prepupa agent.
Implements state machine controlling prepupal behaviour. Prepupae call st_Develop() to increment age until the individual-specific developmental duration is reached, at which point pupation occurs.
State Machine Logic
toOsmias_InitialState: Entry point, transitions immediately to Develop
toOsmias_Develop: Increments age/days, checks mortality, may transition to NextStage
toOsmias_NextStage: Triggers pupation via st_Pupate(), creating pupa object
toOsmias_Die: Executes death, removes from nest and simulation
Biological Context
During the prepupal stage, individuals are constructing the cocoon, voiding waste products, and undergoing preliminary physiological changes. These activities are behavioural and physiological rather than simply growth-based, potentially explaining why simple degree-day models fit poorly. Elevated mortality (0.3% daily, double that of eggs/larvae) reflects the physiological stress of this transitional stage.
See also
st_Develop() for time-based development
st_Pupate() for transition to pupal stage
Osmia prepupa behaviour is simple. It calls develop until the prepupa pupates or dies.
Reimplemented from Osmia_Larva.
Reimplemented in Osmia_Female, Osmia_InCocoon, and Osmia_Pupa.
Definition at line 2090 of file Osmia_dox.cpp.
References Osmia_Base::m_CurrentOState, st_Develop(), Osmia_Base::st_Dying(), st_Pupate(), toOsmias_Develop, toOsmias_Die, toOsmias_InitialState, and toOsmias_NextStage.
Member Data Documentation
m_myOsmiaPrepupaDevelTotalDays
double Osmia_Prepupa::m_myOsmiaPrepupaDevelTotalDays protected
Individual-specific prepupal development duration (days).
Drawn at prepupa creation from uniform distribution: base value (45 days) ±10%. Creates individual variation in development timing. Value remains constant for this individual's prepupal stage.
Biological Basis
Prepupal duration varies substantially between individuals even under identical conditions, reflecting genetic variation, maternal effects, and provision quality effects not explicitly captured otherwise. This stochastic variation prevents unrealistic synchronous pupation.
Definition at line 401 of file Osmia_enh_PART2_LifeStages.h.
Referenced by Osmia_Prepupa(), and st_Develop().
The documentation for this class was generated from the following files:
src/Osmia_enh_PART2_LifeStages.h
src/Osmia_dox.cpp