Osmia bicornis Population Model: Osmia_Egg Class Reference
Osmia_Egg Class Reference
First life stage - egg developing within sealed nest cell.
#include <Osmia_enh_PART2_LifeStages.h>
Public Member Functions
Osmia_Egg (struct_Osmia *data)
Constructor for new egg object.
virtual void ReInit (struct_Osmia *data)
Reinitialize egg object from object pool.
virtual ~Osmia_Egg ()
Destructor.
virtual void Step (void)
Main step function executing egg behaviour.
double GetAgeDegrees ()
Get accumulated degree-days.
void SetAgeDegrees (unsigned a_agedegrees)
Set accumulated degree-days (used during object reinitialization).
Public Member Functions inherited from Osmia_Base
Osmia_Base (struct_Osmia *data)
Constructor creating new Osmia_Base individual.
void ReInit (struct_Osmia *data)
Reinitialize object from object pool.
virtual ~Osmia_Base ()
Virtual destructor ensuring proper cleanup in derived classes.
virtual void st_Dying (void)
Behavioural state for death - cleanup and removal.
virtual void BeginStep (void)
First phase of daily timestep.
virtual void EndStep (void)
Final phase of daily timestep.
int GetAge ()
Get individual's age in days.
void SetAge (int a_age)
Set individual's age in days.
double GetMass ()
Get individual's mass (mg) - interpretation depends on life stage.
void SetMass (double a_mass)
Set individual's mass (mg).
void SetParasitised (TTypeOfOsmiaParasitoids a_status)
Set parasitism status.
TTypeOfOsmiaParasitoids GetParasitised (void)
Get parasitism status.
Osmia_Nest * GetNest ()
Get pointer to nest containing or being provisioned by this individual.
Protected Member Functions
virtual TTypeOfOsmiaState st_Develop (void)
Development state - accumulate degree-days toward hatching.
virtual TTypeOfOsmiaState st_Hatch (void)
Transition state - metamorphose from egg to larva.
virtual bool DailyMortality ()
Daily mortality test for eggs.
Protected Attributes
double m_AgeDegrees = 0.0
Accumulated degree-days toward hatching threshold.
bool m_Sex
Sex of individual (true = female = fertilised egg).
int m_StageAge
Age in days when current life stage was entered.
double m_egg_pest_mortality
Cumulative pesticide mortality probability for this egg.
Protected Attributes inherited from Osmia_Base
TTypeOfOsmiaState m_CurrentOState
Current behavioural state governing agent decisions.
int m_Age
Chronological age in days since egg laying.
Osmia_Population_Manager * m_OurPopulationManager
Pointer to the Osmia population manager instance.
TTypeOfOsmiaParasitoids m_ParasitoidStatus
Records parasitism status of this individual.
Osmia_Nest * m_OurNest
Pointer to nest containing this individual.
double m_Mass
Mass of individual or provision (mg) - interpretation varies by life stage.
int m_foragehours
Hours available for foraging today (decremented as foraging proceeds).
Additional Inherited Members
Static Public Member Functions inherited from Osmia_Base
static void SetParameterValues ()
Populate all static parameters from configuration file.
static void SetTemp (double a_temperature)
Set current daily temperature for all individuals.
static void SetParasitoidManager (OsmiaParasitoid_Population_Manager *a_popman)
Set parasitoid population manager pointer.
Static Protected Attributes inherited from Osmia_Base
static OsmiaParasitoid_Population_Manager * m_OurParasitoidPopulationManager = NULL
Static pointer to parasitoid population manager (if using mechanistic parasitoid model).
static double m_TempToday = -9999
Mean daily temperature (°C) for current timestep.
static int m_TempTodayInt = -9999
Rounded integer temperature for array indexing.
static double m_DailyDevelopmentMortEggs = 0
Daily mortality probability for eggs (probability per day).
static double m_DailyDevelopmentMortLarvae = 0
Daily mortality probability for larvae (probability per day).
static double m_DailyDevelopmentMortPrepupae = 0
Daily mortality probability for prepupae (probability per day).
static double m_DailyDevelopmentMortPupae = 0
Daily mortality probability for pupae (probability per day).
static double m_OsmiaEggDevelTotalDD = 0
Total degree-days required for egg development to hatching.
static double m_OsmiaEggDevelThreshold = 0
Lower developmental threshold temperature for eggs (°C).
static double m_OsmiaLarvaDevelTotalDD = 0
Total degree-days required for larval development to prepupal stage.
static double m_OsmiaLarvaDevelThreshold = 0
Lower developmental threshold temperature for larvae (°C).
static double m_OsmiaPupaDevelTotalDD = 0
Total degree-days required for pupal development to adult eclosion.
static double m_OsmiaPupaDevelThreshold = 0
Lower developmental threshold temperature for pupae (°C).
static double m_OsmiaPrepupalDevelTotalDays = 0
Total days for prepupal development at optimal temperature.
static double m_OsmiaPrepupalDevelTotalDays10pct = 0
Pre-computed 10% of prepupal development time.
static double m_OsmiaInCocoonOverwinteringTempThreshold = 0
Temperature threshold (°C) for accumulating overwintering degree-days.
static double m_OsmiaInCocoonEmergenceTempThreshold = 0
Temperature threshold (°C) for post-diapause emergence counter.
static double m_OsmiaInCocoonPrewinteringTempThreshold = 0
Temperature threshold (°C) for accumulating prewintering degree-days.
static double m_OsmiaInCocoonWinterMortConst = 0.0
Intercept for overwintering mortality equation.
static double m_OsmiaInCocoonWinterMortSlope = 0.0
Slope for overwintering mortality equation.
static double m_OsmiaInCocoonEmergCountConst = 0.0
Intercept for emergence counter equation.
static double m_OsmiaInCocoonEmergCountSlope = 0.0
Slope for emergence counter equation.
static double m_OsmiaFemaleMassFromProvMassConst = 0.0
Intercept for calculating female mass from provision mass.
static double m_OsmiaFemaleMassFromProvMassSlope = 0.0
Slope for calculating female mass from provision mass.
static double m_MaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for male nest cells (mg).
static double m_MaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for male nest cells (mg).
static double m_FemaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxMass = 0.0
Maximum female adult mass (mg) - sets upper bound for provision mass calculations.
static double m_FemaleMinMass = 0.0
Minimum female adult mass (mg) - sets lower bound for provision mass calculations.
static double m_MaleMaxMass = 0.0
Maximum male adult mass (mg) - males are smaller than females.
static double m_PollenScoreToMg = 0.0
Conversion factor from pollen availability score to provisioned mass (mg pollen per day).
static double m_DensityDependentPollenRemovalConst = 0.0
Parameter linking pollen depletion to Osmia population density.
static double m_MinimumCellConstructionTime = 0.0
Minimum time (days) required to construct and provision one nest cell.
static double m_MaximumCellConstructionTime = 0.0
Maximum time (days) required to construct and provision one nest cell.
static int m_TotalNestsPossible = 0
Maximum number of nests a female can complete in her lifetime.
static double m_BombylidProbability = 0.0
Baseline probability of bombyliid fly parasitism per open nest cell.
static double m_ParasitismProbToTimeCellOpen = 0.0
Conversion factor relating cell open time (days) to parasitism probability.
static vector< double > m_ParasitoidAttackChance = {}
Per-capita parasitoid attack probabilities for mechanistic parasitoid model.
static double m_OsmiaFemaleR50distance = 0.0
Typical homing distance - distance at which 50% of females cannot return to nest (m).
static double m_OsmiaFemaleR90distance = 0.0
Maximum homing distance - distance at which 90% of females cannot return (m).
static int m_OsmiaFemalePrenesting = 0
Duration of prenesting period after emergence (days).
static int m_OsmiaFemaleLifespan = 0
Maximum adult female lifespan (days).
static probability_distribution m_generalmovementdistances = probability_distribution(cfg_OsmiaGeneralMovementProbType.value(), cfg_OsmiaGenerallMovementProbArgs.value())
Probability distribution for foraging and nest-searching movements.
static probability_distribution m_dispersalmovementdistances = probability_distribution(cfg_OsmiaDispersalMovementProbType.value(), cfg_OsmiaDispersalMovementProbArgs.value())
Probability distribution for dispersal movements (longer than foraging movements).
static probability_distribution m_eggspernestdistribution = probability_distribution(cfg_OsmiaEggsPerNestProbType.value(), cfg_OsmiaEggsPerNestProbArgs.value())
Probability distribution for planned eggs per nest.
static probability_distribution m_exp_ZeroToOne = probability_distribution("BETA", "1.0, 5.0")
Exponential-like probability distribution over range [0,1].
static double m_CocoonToProvisionMass = 0.0
Mass conversion ratio from cocoon mass to provision mass required.
static double m_ProvisionToCocoonMass = 0.0
Mass conversion ratio from provision mass to resulting cocoon mass.
static double m_TotalProvisioningMassLoss = 0.0
Total provision mass loss from first to last egg in a nest (mg).
static double m_TotalProvisioningMassLossRange = 0.0
Stochastic range around total provisioning mass loss (mg).
static double m_TotalProvisioningMassLossRangeX2 = 0.0
Pre-computed double of mass loss range for efficiency.
static bool m_UsingMechanisticParasitoids = false
Flag selecting parasitism model: true=mechanistic population model, false=simple probabilities.
static double m_OsmiaFemaleBckMort = 0.0
Daily background mortality for adult females outside nest (probability per day).
static int m_OsmiaFemaleMinEggsPerNest = 0
Minimum eggs planned per nest (sets lower bound for egg planning distribution).
static int m_OsmiaFindNestAttemptNo = 0
Number of attempts allowed for finding suitable nest location before giving up.
static int m_OsmiaFemaleMaxEggsPerNest = 0
Maximum eggs planned per nest (sets upper bound for egg planning distribution).
static probability_distribution m_emergenceday = probability_distribution(cfg_OsmiaEmergenceProbType.value(), cfg_OsmiaEmergenceProbArgs.value())
Probability distribution for day of emergence relative to population mean.
Detailed Description
First life stage - egg developing within sealed nest cell.
Osmia_Egg represents the egg stage from laying through hatching. Development is driven by degree-day accumulation above the threshold temperature. Eggs experience daily mortality risk and may be parasitised if the cell was compromised during the vulnerable period whilst open.
Biological Foundation
O. bicornis eggs are laid on top of provision masses in sealed cells. Development time depends strongly on temperature - warmer conditions accelerate hatching, cooler temperatures slow or halt development. Laboratory studies (Giejdasz & Wilkaniec 2002, Radmacher & Strohm 2011) provide baseline parameters, though implementation values are calibrated for field realism.
Development Model
Uses simple degree-day accumulation: each day above threshold temperature adds (T - T_threshold) to m_AgeDegrees. When m_AgeDegrees reaches m_OsmiaEggDevelTotalDD (86 DD), egg hatches and individual transitions to Osmia_Larva.
Mortality
Daily mortality probability applied each day (m_DailyDevelopmentMortEggs = 0.0014). Represents combined effects of desiccation, fungal infection, temperature extremes, and developmental failures. Mortality is temperature-independent in implementation despite some evidence of temperature effects.
Sex Determination
Sex is determined at laying (set by parent female based on sex allocation decisions). Female eggs are fertilised (diploid), male eggs unfertilised (haploid). Sex persists through all life stages though males are not explicitly modelled as adults.
Difference from Formal Model
The formal model specified development parameters; implementation adjusted them substantially for field realism (see Osmia_Base parameter documentation). Mortality implementation matches formal model exactly.
See also
Osmia_Base for development parameters
st_Develop() for degree-day accumulation logic
st_Hatch() for transition to larval stage
Definition at line 40 of file Osmia_enh_PART2_LifeStages.h.
Constructor & Destructor Documentation
Osmia_Egg()
Osmia_Egg::Osmia_Egg (struct_Osmia * data)
Constructor for new egg object.
Constructor for Osmia_Egg from initialization data.
Parameters
data Initialization data including parent info, nest location, sex, provision mass
Initializes egg attributes, sets m_AgeDegrees to 0, records sex, links to nest. Egg begins development immediately after creation.
Creates a new egg agent from oviposition event data. Initializes stage-specific variables including degree-day accumulation tracking and optional pesticide mortality flag.
Parameters
data Pointer to struct_Osmia containing initialization data including location, age, mass, sex, nest association, and optional pesticide exposure status
Biological Context
Eggs are laid by females into provisioned nest cells. Each egg represents a potential offspring with predetermined sex (based on provision mass accumulated by the mother) and potential parasitism status. Eggs begin with zero degree-day accumulation and progress through temperature-dependent development until hatching.
Implementation Notes
The constructor chains to Osmia_Base to handle common initialization, then sets egg-specific state. Under the OSMIA_PESTICIDE_ENGINE compilation flag, eggs may inherit a pesticide mortality probability from contaminated provisions or spray exposure during nest provisioning.
See also
ReInit() for state variable initialization
struct_Osmia for initialization data structure
Definition at line 1583 of file Osmia_dox.cpp.
References struct_Osmia::age, m_AgeDegrees, m_egg_pest_mortality, Osmia_Base::m_OurNest, m_Sex, m_StageAge, struct_Osmia::nest, Osmia_Base::Osmia_Base(), struct_Osmia::pest_mortality, ReInit(), and struct_Osmia::sex.
Referenced by Osmia_Larva::Osmia_Larva().
~Osmia_Egg()
Osmia_Egg::~Osmia_Egg (void) virtual
Destructor.
Destructor for Osmia_Egg.
Empty destructor as cleanup is handled by base class. Eggs transition to larvae upon hatching rather than being destroyed.
Definition at line 1556 of file Osmia_dox.cpp.
Member Function Documentation
DailyMortality()
virtual bool Osmia_Egg::DailyMortality () inline protected virtual
Daily mortality test for eggs.
Returns
true if dies, false if survives
Simple probabilistic test: generates uniform random number [0,1], compares to m_DailyDevelopmentMortEggs (0.0014). Independent of temperature, age, or provision mass.
Biological Interpretation
Represents average daily hazard from all mortality sources. Temperature-independence is simplification due to insufficient data on temperature-mortality relationships. Conservative choice given uncertainty.
Reimplemented in Osmia_Larva, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 176 of file Osmia_enh_PART2_LifeStages.h.
References Osmia_Base::m_DailyDevelopmentMortEggs.
Referenced by st_Develop().
GetAgeDegrees()
double Osmia_Egg::GetAgeDegrees () inline
Get accumulated degree-days.
Definition at line 114 of file Osmia_enh_PART2_LifeStages.h.
References m_AgeDegrees.
ReInit()
void Osmia_Egg::ReInit (struct_Osmia * data) virtual
Reinitialize egg object from object pool.
Reinitialize an existing Osmia_Egg object with new data.
Parameters
data New initialization data
Resets all egg-specific attributes for object reuse, avoiding allocation overhead.
Used when recycling egg objects rather than creating new ones. Resets all stage-specific state variables whilst preserving the object itself for memory efficiency.
Parameters
data Pointer to struct_Osmia containing new initialization data
Implementation Rationale
Object recycling substantially improves performance in population models with frequent agent creation and destruction. Reusing existing objects avoids memory allocation/deallocation overhead whilst maintaining clean initialization of state variables.
Reimplemented in Osmia_Female, Osmia_InCocoon, Osmia_Larva, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 1607 of file Osmia_dox.cpp.
References struct_Osmia::age, m_AgeDegrees, m_egg_pest_mortality, Osmia_Base::m_OurNest, m_Sex, m_StageAge, struct_Osmia::nest, struct_Osmia::pest_mortality, Osmia_Base::ReInit(), and struct_Osmia::sex.
Referenced by Osmia_Egg(), and Osmia_Larva::ReInit().
SetAgeDegrees()
void Osmia_Egg::SetAgeDegrees (unsigned a_agedegrees) inline
Set accumulated degree-days (used during object reinitialization).
Definition at line 117 of file Osmia_enh_PART2_LifeStages.h.
References m_AgeDegrees.
st_Develop()
TTypeOfOsmiaState Osmia_Egg::st_Develop (void) protected virtual
Development state - accumulate degree-days toward hatching.
Execute daily egg development and mortality.
Returns
Next state (st_Hatch if threshold reached, st_Develop to continue, or st_Die)
Each day:
Check if temperature exceeds threshold (m_OsmiaEggDevelThreshold)
If yes: add (T - threshold) to m_AgeDegrees
Check if m_AgeDegrees >= m_OsmiaEggDevelTotalDD
If yes: return st_Hatch
Apply daily mortality test
If survives: return st_Develop (continue development)
Temperature Handling
Days below threshold add zero DD - development is suspended but mortality still applies. This can extend absolute calendar time to hatching if prolonged cool periods occur.
Difference from Formal Model
IMPLEMENTATION MATCH - Logic follows formal model specification exactly. Parameter values differ (see Osmia_Base documentation) but algorithm structure is identical.
Accumulates degree-days based on daily temperature and lower developmental threshold. Checks mortality from both background causes and optional pesticide exposure. Returns state indicating whether to continue development, hatch, or die.
Returns
Next state: toOsmias_Die if mortality occurs, toOsmias_NextStage if development completes, toOsmias_Develop to continue development
Biological Rationale
Egg development follows a simple degree-day accumulation model: development proceeds only when temperature exceeds the LDT (0°C), accumulating thermal energy until the SET (86 DD) is reached. Mortality from background causes (0.14% daily) occurs first, followed by optional threshold-based pesticide mortality if the egg was contaminated during oviposition or nest provisioning.
Implementation Details
Development and mortality only occur when the nest is sealed (GetIsOpen() returns false). Unsealed nests indicate the mother is still provisioning, during which eggs do not develop (biological realism: development does not commence until the cell is sealed and temperatures stabilize). Temperature is retrieved daily via m_TempToday (set by population manager before agent steps).
Degree-Day Calculation
DD = max(0, daily_temperature - threshold)
Negative DD values (temperature below threshold) are ignored; development does not regress. Only positive thermal energy accumulates towards the developmental requirement.
Pesticide Mortality
When compiled with OSMIA_PESTICIDE_ENGINE and threshold-based response enabled, eggs face a single mortality test using m_egg_pest_mortality probability. If the egg survives this test, the pesticide mortality probability is reset to zero (one-time exposure rather than cumulative).
Sensitivity
The egg stage is relatively short (typically 7-14 days), so daily mortality and developmental rate both have moderate population-level impacts. However, because all individuals pass through the egg stage, cumulative effects are non-trivial.
See also
DailyMortality() for background mortality calculation
cfg_OsmiaEggDevelThreshold for LDT parameter
cfg_OsmiaEggDevelTotalDD for SET parameter
Reimplemented in Osmia_Female, Osmia_InCocoon, Osmia_Larva, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 1709 of file Osmia_dox.cpp.
References cfg_OsmiaEggThresholdBasedPesticideResponse(), DailyMortality(), Osmia_Base::m_Age, m_AgeDegrees, m_egg_pest_mortality, Osmia_Base::m_OsmiaEggDevelThreshold, Osmia_Base::m_OsmiaEggDevelTotalDD, Osmia_Base::m_OurNest, Osmia_Base::m_TempToday, toOsmias_Develop, toOsmias_Die, and toOsmias_NextStage.
Referenced by Step().
st_Hatch()
TTypeOfOsmiaState Osmia_Egg::st_Hatch (void) protected virtual
Transition state - metamorphose from egg to larva.
Execute egg hatching, creating larva and removing egg.
Returns
Next state (always returns st_Die as this object is deleted)
Hatching sequence:
Signal population manager to create new Osmia_Larva object
Transfer essential attributes (sex, mass, nest pointer, age, parasitism status, m_AgeDegrees)
Population manager updates nest's cell pointer to new larva object
This egg object is deleted
Larva begins its developmental cycle
Implementation Pattern
This metamorphosis pattern (delete old object, create new object of next class, transfer attributes) is used at all stage transitions. It maintains clean separation between life stages whilst preserving individual identity through attribute transfer.
Biological Accuracy
Represents the ecological concept of "hatching" - egg case breaks, first instar larva emerges and begins feeding on provision mass. In model terms, this is object type change without loss of individual continuity.
Creates a new Osmia_Larva object inheriting all state from the egg (location, age, mass, sex, parasitism status, nest association), then removes the egg object from simulation.
Returns
toOsmias_Emerged (return value not used as object is destroyed)
Biological Context
Hatching represents eclosion of the first-instar larva from the egg chorion. All egg state information transfers to the larva: predetermined sex (based on maternal provision allocation), potential parasitism status (if mother encountered parasites during provisioning), accumulated age (important for phenology tracking), and nest association (determines subsequent development location and mortality risk).
Implementation Strategy
The struct_Osmia temporary object packages all necessary state for larva initialization. The population manager's CreateObjects() method handles larva object creation and insertion into the simulation, including appropriate list management and memory handling. KillThis() then removes the egg object, with cleanup handled by the population manager.
Model Outputs
Under OSMIATESTING compilation flag, records egg stage duration for model verification and output generation. This tracking helps validate developmental timing against field observations and supports analyses of phenological variation.
See also
Osmia_Larva constructor for larva initialization
Osmia_Population_Manager::CreateObjects() for object creation mechanism
struct_Osmia for state transfer data structure
Creates a new larva object and passes the data from the egg to it, then signals egg object removal.
Definition at line 1766 of file Osmia_dox.cpp.
References struct_Osmia::age, struct_Osmia::L, Osmia_Base::m_Age, Osmia_Base::m_Mass, Osmia_Base::m_OurNest, Osmia_Base::m_OurPopulationManager, Osmia_Base::m_ParasitoidStatus, m_Sex, m_StageAge, struct_Osmia::mass, struct_Osmia::nest, struct_Osmia::OPM, struct_Osmia::parasitised, struct_Osmia::sex, to_OsmiaLarva, toOsmias_Emerged, struct_Osmia::x, and struct_Osmia::y.
Referenced by Step().
Step()
void Osmia_Egg::Step (void) virtual
Main step function executing egg behaviour.
Execute daily time step for egg agent.
Calls st_Develop to accumulate degree-days and test for hatching. Applies daily mortality test. Transitions to Osmia_Larva upon hatching or to death upon mortality.
Implements state machine controlling egg behaviour. Eggs primarily call st_Develop() to accumulate degree-days until hatching. The state machine prevents multiple executions per day and handles transitions between development, hatching, and death.
State Machine Logic
toOsmias_InitialState: Entry point, transitions immediately to Develop
toOsmias_Develop: Accumulates degree-days, checks mortality, may transition to NextStage
toOsmias_NextStage: Triggers hatching via st_Hatch(), creating larva object
toOsmias_Die: Executes death, removes from nest and simulation
Implementation Notes
The m_StepDone flag prevents re-execution within the same day. State transitions occur within a single Step() call when appropriate (e.g., completing development and immediately hatching), whilst mortality causes immediate termination.
See also
st_Develop() for degree-day accumulation and mortality checks
st_Hatch() for transition to larval stage
Osmia egg behaviour is simple. It calls develop until the egg hatches or dies.
Reimplemented from Osmia_Base.
Reimplemented in Osmia_Female, Osmia_InCocoon, Osmia_Larva, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 1639 of file Osmia_dox.cpp.
References Osmia_Base::m_CurrentOState, st_Develop(), Osmia_Base::st_Dying(), st_Hatch(), toOsmias_Develop, toOsmias_Die, toOsmias_InitialState, and toOsmias_NextStage.
Member Data Documentation
m_AgeDegrees
double Osmia_Egg::m_AgeDegrees = 0.0 protected
Accumulated degree-days toward hatching threshold.
Incremented daily by (T_today - T_threshold) when temperature exceeds threshold. When m_AgeDegrees >= m_OsmiaEggDevelTotalDD, egg hatches.
Implementation Note
Initialized to 0.0 at egg creation. Can be queried for monitoring development progress. Persists through metamorphosis - larvae inherit m_AgeDegrees to continue development tracking.
Definition at line 53 of file Osmia_enh_PART2_LifeStages.h.
Referenced by GetAgeDegrees(), Osmia_Egg(), Osmia_Prepupa::Osmia_Prepupa(), ReInit(), Osmia_InCocoon::ReInit(), SetAgeDegrees(), st_Develop(), Osmia_InCocoon::st_Develop(), Osmia_Larva::st_Develop(), Osmia_Prepupa::st_Develop(), and Osmia_Pupa::st_Develop().
m_egg_pest_mortality
double Osmia_Egg::m_egg_pest_mortality protected
Cumulative pesticide mortality probability for this egg.
Tracks pesticide exposure effects when pesticide module is active. Represents both maternal transfer of pesticides via contaminated provisions and direct exposure if nest is sprayed. Used primarily for pesticide scenario testing.
Definition at line 85 of file Osmia_enh_PART2_LifeStages.h.
Referenced by Osmia_Egg(), ReInit(), and st_Develop().
m_Sex
bool Osmia_Egg::m_Sex protected
Sex of individual (true = female = fertilised egg).
Determined at laying by parent female's sex allocation algorithm. Female eggs are fertilised (diploid, sex=true), male eggs unfertilised (haploid, sex=false). Sex persists through all life stages.
Biological Basis
Hymenoptera have haplodiploid sex determination: fertilised eggs develop as females, unfertilised as males. Females control fertilisation during egg laying, enabling strategic sex allocation. O. bicornis typically places female eggs (larger provisions) deep in nest, male eggs (smaller provisions) near entrance.
Definition at line 68 of file Osmia_enh_PART2_LifeStages.h.
Referenced by Osmia_Egg(), ReInit(), Osmia_InCocoon::st_Emerge(), Osmia_Pupa::st_Emerge(), st_Hatch(), Osmia_Larva::st_Prepupate(), and Osmia_Prepupa::st_Pupate().
m_StageAge
int Osmia_Egg::m_StageAge protected
Age in days when current life stage was entered.
Records absolute age (m_Age) at stage transition. Used to calculate stage duration for output and validation. For eggs, m_StageAge equals 0 (stage entered at birth).
Definition at line 76 of file Osmia_enh_PART2_LifeStages.h.
Referenced by Osmia_Egg(), ReInit(), Osmia_InCocoon::st_Emerge(), Osmia_Pupa::st_Emerge(), st_Hatch(), Osmia_Larva::st_Prepupate(), and Osmia_Prepupa::st_Pupate().
The documentation for this class was generated from the following files:
src/Osmia_enh_PART2_LifeStages.h
src/Osmia_dox.cpp