Osmia bicornis Population Model: Osmia_Pupa Class Reference
Osmia_Pupa Class Reference
Pupal metamorphosis stage.
#include <Osmia_enh_PART2_LifeStages.h>
Public Member Functions
Osmia_Pupa (struct_Osmia *data)
Constructor transferring from prepupa.
virtual void ReInit (struct_Osmia *data)
Reinitialize pupa from object pool.
virtual ~Osmia_Pupa ()
Destructor.
virtual void Step (void)
Main step function.
Public Member Functions inherited from Osmia_Prepupa
Osmia_Prepupa (struct_Osmia *data)
Constructor transferring from larva to prepupa.
virtual ~Osmia_Prepupa ()
Destructor.
Public Member Functions inherited from Osmia_Larva
Osmia_Larva (struct_Osmia *data)
Constructor for new larva (created during egg hatching)
virtual ~Osmia_Larva ()
Destructor.
Public Member Functions inherited from Osmia_Egg
Osmia_Egg (struct_Osmia *data)
Constructor for new egg object.
virtual ~Osmia_Egg ()
Destructor.
double GetAgeDegrees ()
Get accumulated degree-days.
void SetAgeDegrees (unsigned a_agedegrees)
Set accumulated degree-days (used during object reinitialization)
Public Member Functions inherited from Osmia_Base
Osmia_Base (struct_Osmia *data)
Constructor creating new Osmia_Base individual.
void ReInit (struct_Osmia *data)
Reinitialize object from object pool.
virtual ~Osmia_Base ()
Virtual destructor ensuring proper cleanup in derived classes.
virtual void st_Dying (void)
Behavioural state for death - cleanup and removal.
virtual void BeginStep (void)
First phase of daily timestep.
virtual void EndStep (void)
Final phase of daily timestep.
int GetAge ()
Get individual's age in days.
void SetAge (int a_age)
Set individual's age in days.
double GetMass ()
Get individual's mass (mg) - interpretation depends on life stage.
void SetMass (double a_mass)
Set individual's mass (mg)
void SetParasitised (TTypeOfOsmiaParasitoids a_status)
Set parasitism status.
TTypeOfOsmiaParasitoids GetParasitised (void)
Get parasitism status.
Osmia_Nest * GetNest ()
Get pointer to nest containing or being provisioned by this individual.
Protected Member Functions
virtual TTypeOfOsmiaState st_Develop (void)
Development state - accumulate degree-days toward eclosion.
virtual TTypeOfOsmiaState st_Emerge (void)
Transition state - eclosion from pupa to adult-in-cocoon.
virtual bool DailyMortality ()
Daily mortality test for pupae.
Protected Member Functions inherited from Osmia_Prepupa
virtual TTypeOfOsmiaState st_Pupate (void)
Transition state - metamorphose from prepupa to pupa.
Protected Member Functions inherited from Osmia_Larva
virtual TTypeOfOsmiaState st_Prepupate (void)
Transition state - metamorphose from larva to prepupa.
Protected Member Functions inherited from Osmia_Egg
virtual TTypeOfOsmiaState st_Hatch (void)
Transition state - metamorphose from egg to larva.
Additional Inherited Members
Static Public Member Functions inherited from Osmia_Base
static void SetParameterValues ()
Populate all static parameters from configuration file.
static void SetTemp (double a_temperature)
Set current daily temperature for all individuals.
static void SetParasitoidManager (OsmiaParasitoid_Population_Manager *a_popman)
Set parasitoid population manager pointer.
Protected Attributes inherited from Osmia_Prepupa
double m_myOsmiaPrepupaDevelTotalDays
Individual-specific prepupal development duration (days)
Protected Attributes inherited from Osmia_Egg
double m_AgeDegrees = 0.0
Accumulated degree-days toward hatching threshold.
bool m_Sex
Sex of individual (true = female = fertilised egg)
int m_StageAge
Age in days when current life stage was entered.
double m_egg_pest_mortality
Cumulative pesticide mortality probability for this egg.
Protected Attributes inherited from Osmia_Base
TTypeOfOsmiaState m_CurrentOState
Current behavioural state governing agent decisions.
int m_Age
Chronological age in days since egg laying.
Osmia_Population_Manager * m_OurPopulationManager
Pointer to the Osmia population manager instance.
TTypeOfOsmiaParasitoids m_ParasitoidStatus
Records parasitism status of this individual.
Osmia_Nest * m_OurNest
Pointer to nest containing this individual.
double m_Mass
Mass of individual or provision (mg) - interpretation varies by life stage.
int m_foragehours
Hours available for foraging today (decremented as foraging proceeds)
Static Protected Attributes inherited from Osmia_Base
static OsmiaParasitoid_Population_Manager * m_OurParasitoidPopulationManager = NULL
Static pointer to parasitoid population manager (if using mechanistic parasitoid model)
static double m_TempToday = -9999
Mean daily temperature (°C) for current timestep.
static int m_TempTodayInt = -9999
Rounded integer temperature for array indexing.
static double m_DailyDevelopmentMortEggs = 0
Daily mortality probability for eggs (probability per day)
static double m_DailyDevelopmentMortLarvae = 0
Daily mortality probability for larvae (probability per day)
static double m_DailyDevelopmentMortPrepupae = 0
Daily mortality probability for prepupae (probability per day)
static double m_DailyDevelopmentMortPupae = 0
Daily mortality probability for pupae (probability per day)
static double m_OsmiaEggDevelTotalDD = 0
Total degree-days required for egg development to hatching.
static double m_OsmiaEggDevelThreshold = 0
Lower developmental threshold temperature for eggs (°C)
static double m_OsmiaLarvaDevelTotalDD = 0
Total degree-days required for larval development to prepupal stage.
static double m_OsmiaLarvaDevelThreshold = 0
Lower developmental threshold temperature for larvae (°C)
static double m_OsmiaPupaDevelTotalDD = 0
Total degree-days required for pupal development to adult eclosion.
static double m_OsmiaPupaDevelThreshold = 0
Lower developmental threshold temperature for pupae (°C)
static double m_OsmiaPrepupalDevelTotalDays = 0
Total days for prepupal development at optimal temperature.
static double m_OsmiaPrepupalDevelTotalDays10pct = 0
Pre-computed 10% of prepupal development time.
static double m_OsmiaInCocoonOverwinteringTempThreshold = 0
Temperature threshold (°C) for accumulating overwintering degree-days.
static double m_OsmiaInCocoonEmergenceTempThreshold = 0
Temperature threshold (°C) for post-diapause emergence counter.
static double m_OsmiaInCocoonPrewinteringTempThreshold = 0
Temperature threshold (°C) for accumulating prewintering degree-days.
static double m_OsmiaInCocoonWinterMortConst = 0.0
Intercept for overwintering mortality equation.
static double m_OsmiaInCocoonWinterMortSlope = 0.0
Slope for overwintering mortality equation.
static double m_OsmiaInCocoonEmergCountConst = 0.0
Intercept for emergence counter equation.
static double m_OsmiaInCocoonEmergCountSlope = 0.0
Slope for emergence counter equation.
static double m_OsmiaFemaleMassFromProvMassConst = 0.0
Intercept for calculating female mass from provision mass.
static double m_OsmiaFemaleMassFromProvMassSlope = 0.0
Slope for calculating female mass from provision mass.
static double m_MaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for male nest cells (mg)
static double m_MaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for male nest cells (mg)
static double m_FemaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for female nest cells (mg)
static double m_FemaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for female nest cells (mg)
static double m_FemaleMaxMass = 0.0
Maximum female adult mass (mg) - sets upper bound for provision mass calculations.
static double m_FemaleMinMass = 0.0
Minimum female adult mass (mg) - sets lower bound for provision mass calculations.
static double m_MaleMaxMass = 0.0
Maximum male adult mass (mg) - males are smaller than females.
static double m_PollenScoreToMg = 0.0
Conversion factor from pollen availability score to provisioned mass (mg pollen per day)
static double m_DensityDependentPollenRemovalConst = 0.0
Parameter linking pollen depletion to Osmia population density.
static double m_MinimumCellConstructionTime = 0.0
Minimum time (days) required to construct and provision one nest cell.
static double m_MaximumCellConstructionTime = 0.0
Maximum time (days) required to construct and provision one nest cell.
static int m_TotalNestsPossible = 0
Maximum number of nests a female can complete in her lifetime.
static double m_BombylidProbability = 0.0
Baseline probability of bombyliid fly parasitism per open nest cell.
static double m_ParasitismProbToTimeCellOpen = 0.0
Conversion factor relating cell open time (days) to parasitism probability.
static vector< double > m_ParasitoidAttackChance = {}
Per-capita parasitoid attack probabilities for mechanistic parasitoid model.
static double m_OsmiaFemaleR50distance = 0.0
Typical homing distance - distance at which 50% of females cannot return to nest (m)
static double m_OsmiaFemaleR90distance = 0.0
Maximum homing distance - distance at which 90% of females cannot return (m)
static int m_OsmiaFemalePrenesting = 0
Duration of prenesting period after emergence (days)
static int m_OsmiaFemaleLifespan = 0
Maximum adult female lifespan (days)
static probability_distribution m_generalmovementdistances = probability_distribution(cfg_OsmiaGeneralMovementProbType.value(), cfg_OsmiaGenerallMovementProbArgs.value())
Probability distribution for foraging and nest-searching movements.
static probability_distribution m_dispersalmovementdistances = probability_distribution(cfg_OsmiaDispersalMovementProbType.value(), cfg_OsmiaDispersalMovementProbArgs.value())
Probability distribution for dispersal movements (longer than foraging movements)
static probability_distribution m_eggspernestdistribution = probability_distribution(cfg_OsmiaEggsPerNestProbType.value(), cfg_OsmiaEggsPerNestProbArgs.value())
Probability distribution for planned eggs per nest.
static probability_distribution m_exp_ZeroToOne = probability_distribution("BETA", "1.0, 5.0")
Exponential-like probability distribution over range [0,1].
static double m_CocoonToProvisionMass = 0.0
Mass conversion ratio from cocoon mass to provision mass required.
static double m_ProvisionToCocoonMass = 0.0
Mass conversion ratio from provision mass to resulting cocoon mass.
static double m_TotalProvisioningMassLoss = 0.0
Total provision mass loss from first to last egg in a nest (mg)
static double m_TotalProvisioningMassLossRange = 0.0
Stochastic range around total provisioning mass loss (mg)
static double m_TotalProvisioningMassLossRangeX2 = 0.0
Pre-computed double of mass loss range for efficiency.
static bool m_UsingMechanisticParasitoids = false
Flag selecting parasitism model: true=mechanistic population model, false=simple probabilities.
static double m_OsmiaFemaleBckMort = 0.0
Daily background mortality for adult females outside nest (probability per day)
static int m_OsmiaFemaleMinEggsPerNest = 0
Minimum eggs planned per nest (sets lower bound for egg planning distribution)
static int m_OsmiaFindNestAttemptNo = 0
Number of attempts allowed for finding suitable nest location before giving up.
static int m_OsmiaFemaleMaxEggsPerNest = 0
Maximum eggs planned per nest (sets upper bound for egg planning distribution)
static probability_distribution m_emergenceday = probability_distribution(cfg_OsmiaEmergenceProbType.value(), cfg_OsmiaEmergenceProbArgs.value())
Probability distribution for day of emergence relative to population mean.
Detailed Description
Pupal metamorphosis stage.
Osmia_Pupa represents active metamorphosis from larval to adult form. Returns to degree-day development model (like egg/larva) after prepupal time-based development. Pupal stage ends with eclosion - adult emerges from pupal exuviae within cocoon, entering overwintering adult stage.
Biological Foundation
During pupation, tissues reorganize from larval to adult configuration through histolysis and histogenesis. This metabolically expensive process is temperature-sensitive - higher temperatures accelerate metamorphosis. Pupae remain within cocoon, protected but vulnerable to extreme temperatures.
Development Model
Returns to degree-day accumulation after prepupal time-based development. However, m_AgeDegrees is reset at pupation (not carried forward from earlier stages) because pupal DD requirements are independent of earlier development history. Accumulates (T - threshold) daily until reaching m_OsmiaPupaDevelTotalDD, then transitions to overwintering adult.
Calibration
MAJOR DIFFERENCE: Pupal parameters show largest calibration adjustment in model. Formal model: 272.3 DD with 13.2°C threshold. Implementation: 570 DD with 1.1°C threshold. This compensatory adjustment maintains realistic development timing under field temperatures whilst preventing developmental failure. Code comment explicitly notes: "changed from 13.2 to prevent pupal death".
Mortality
Very low (0.003 daily), same as prepupa. Well-protected within cocoon. Most pupal mortality reflects earlier problems (insufficient provisioning) manifesting during energy-intensive metamorphosis.
See also
Osmia_Base for detailed discussion of pupal parameter calibration
Definition at line 436 of file Osmia_enh_PART2_LifeStages.h.
Constructor & Destructor Documentation
Osmia_Pupa()
Osmia_Pupa::Osmia_Pupa (struct_Osmia * data)
Constructor transferring from prepupa.
Constructor for Osmia_Pupa from initialization data.
Creates a new pupa agent undergoing complete metamorphosis within the sealed cocoon.
Parameters
data Pointer to struct_Osmia containing initialization data
Biological Context
Pupae undergo complete metamorphosis, with extensive histolysis of larval tissues (imaginal discs excepted) and histogenesis of adult structures. This process is energetically demanding and developmentally complex, reflected in elevated mortality rates (0.3% daily) similar to prepupae. Pupal development timing is critical for population persistence: development must complete before winter whilst avoiding autumn emergence into unsuitable conditions.
Developmental Model
Uses degree-day accumulation with heavily calibrated parameters: LDT = 1.1°C (reduced from laboratory-derived 13.2°C) and SET = 570 DD (increased from laboratory-derived 272.3 DD). These calibrations prevent premature autumn emergence that occurred with original parameters, ensuring individuals remain in cocoons through winter as pharate adults.
Implementation Strategy
Inherits from Osmia_Prepupa, accessing the full inheritance hierarchy of developmental mechanisms. However, pupae revert to degree-day based development (like eggs and larvae) rather than using the time-based approach of prepupae. This reflects greater confidence in degree-day modelling for this stage despite large calibration adjustments.
See also
cfg_OsmiaPupaDevelTotalDD for SET parameter discussion (570 DD, major calibration)
cfg_OsmiaPupaDevelThreshold for LDT parameter discussion (1.1°C, major calibration)
Definition at line 2285 of file Osmia_dox.cpp.
References ReInit().
~Osmia_Pupa()
Osmia_Pupa::~Osmia_Pupa (void) virtual
Destructor.
Destructor for Osmia_Pupa.
Empty destructor as cleanup is handled by base classes. Pupae transition to overwintering adults (Osmia_InCocoon) upon completing metamorphosis.
Definition at line 2252 of file Osmia_dox.cpp.
Member Function Documentation
DailyMortality()
virtual bool Osmia_Pupa::DailyMortality () inline protected virtual
Daily mortality test for pupae.
Returns
true if dies, false if survives
Uses m_DailyDevelopmentMortPupae (0.003). Low mortality reflects protection of cocooned pupae. Most failures occur if larva was inadequately provisioned, causing pupal metamorphosis to fail (not explicitly modelled - assumed rare).
Reimplemented from Osmia_Prepupa.
Definition at line 498 of file Osmia_enh_PART2_LifeStages.h.
References Osmia_Base::m_DailyDevelopmentMortPupae.
Referenced by st_Develop().
ReInit()
void Osmia_Pupa::ReInit (struct_Osmia * data) virtual
Reinitialize pupa from object pool.
Reinitialize an existing Osmia_Pupa object with new data.
Chains to Osmia_Prepupa::ReInit() to inherit all previous state initialization.
Parameters
data Pointer to struct_Osmia containing new initialization data
Implementation Notes
Pupae inherit the full state variable structure from prepupae but transition to degree-day based development with highly calibrated parameters critical for appropriate overwintering timing.
Reimplemented from Osmia_Prepupa.
Reimplemented in Osmia_InCocoon, and Osmia_Female.
Definition at line 2242 of file Osmia_dox.cpp.
References Osmia_Prepupa::ReInit().
Referenced by Osmia_Pupa(), and Osmia_InCocoon::ReInit().
st_Develop()
TTypeOfOsmiaState Osmia_Pupa::st_Develop (void) protected virtual
Development state - accumulate degree-days toward eclosion.
Execute daily pupal development and mortality.
Returns
Next state (st_Emerge when DD threshold reached, st_Develop to continue, or st_Die)
Standard degree-day logic:
If T > m_OsmiaPupaDevelThreshold (1.1°C): add (T - 1.1) to m_AgeDegrees
When m_AgeDegrees >= m_OsmiaPupaDevelTotalDD (570 DD): transition to adult
Apply daily mortality test
Temperature Response
Very low threshold (1.1°C) means pupal development proceeds across full summer temperature range. High total DD requirement (570) compensates, maintaining appropriate absolute duration. This parameterization essential for preventing developmental failures noted during calibration.
Biological Process
Pupal stage is active metamorphosis. Adult structures (wings, legs, reproductive organs) form from imaginal discs whilst larval tissues are remodelled. Process requires substantial energy and time, reflected in high DD requirement.
Accumulates degree-days based on daily temperature and pupal developmental threshold (1.1°C). Checks background mortality (0.3% daily). Returns state indicating whether to continue metamorphosis, complete development, or die.
Returns
Next state: toOsmias_Die if mortality occurs, toOsmias_NextStage if development completes (570 DD accumulated), toOsmias_Develop to continue metamorphosis
Biological Rationale
Pupal development follows degree-day accumulation but with parameters differing dramatically from laboratory studies. The calibrated LDT (1.1°C) and SET (570 DD) prevent autumn emergence that occurred with original parameters (LDT = 13.2°C, SET = 272.3 DD). The low threshold permits slow developmental accumulation through summer and autumn, whilst the high SET requirement ensures completion takes months rather than weeks.
Implementation Details
The degree-day calculation is standard: DD = max(0, temperature - threshold). Only positive values accumulate; temperatures below threshold cause developmental pause without regression. Temperature retrieval uses SupplyTemp() from the landscape, providing daily ambient conditions.
Critical Timing Considerations
The timing of pupal development completion determines whether individuals overwinter successfully. With calibrated parameters, pupae typically complete metamorphosis in late summer (August-September), becoming pharate adults that remain in cocoons through winter. Original parameters caused completion much earlier, leading to inappropriate emergence in autumn when no floral resources exist.
Difference from Formal Model
MAJOR CALIBRATION: Formal model parameters from laboratory studies (LDT = 13.2°C, SET = 272.3 DD) produced ecologically implausible behaviour (autumn emergence). Implementation uses heavily calibrated parameters (LDT = 1.1°C, SET = 570 DD), representing a 12.1°C threshold reduction and 109% SET increase. This calibration was essential for realistic overwintering phenology, highlighting challenges in transferring laboratory parameters to field conditions.
Rationale for Large Calibration
The calibration acknowledges either: (1) laboratory parameters were measured under different thermal regimes or to different developmental endpoints than field conditions require, (2) unmodelled factors (photoperiod, diapause regulation) influence field phenology beyond simple degree-day accumulation, or (3) the linear degree-day model inadequately captures non-linear temperature responses during metamorphosis. Regardless of cause, the calibration was necessary for ecological realism.
Sensitivity
EXTREMELY HIGH - These parameters are critically sensitive because they determine overwintering vs autumn emergence, which is binary (survive vs perish). Even small parameter changes can shift individuals between these outcomes. This extreme sensitivity necessitated the large calibration adjustments and makes these parameters the highest priority for field validation.
Uncertainty
VERY HIGH - The massive calibration adjustment (12.1°C threshold reduction, 109% SET increase) creates substantial uncertainty. The parameters enable realistic phenology but their biological interpretation is unclear. They likely compensate for missing model components (photoperiod, diapause) or incorrect developmental endpoint definitions. Field validation remains critical.
See also
DailyMortality() for mortality calculation (0.3% daily)
cfg_OsmiaPupaDevelThreshold for LDT parameter (1.1°C, down from 13.2°C)
cfg_OsmiaPupaDevelTotalDD for SET parameter (570 DD, up from 272.3 DD)
Reimplemented from Osmia_Prepupa.
Reimplemented in Osmia_InCocoon, and Osmia_Female.
Definition at line 2405 of file Osmia_dox.cpp.
References DailyMortality(), Osmia_Base::m_Age, Osmia_Egg::m_AgeDegrees, Osmia_Base::m_OsmiaPupaDevelThreshold, Osmia_Base::m_OsmiaPupaDevelTotalDD, toOsmias_Develop, toOsmias_Die, and toOsmias_NextStage.
Referenced by Step().
st_Emerge()
TTypeOfOsmiaState Osmia_Pupa::st_Emerge (void) protected virtual
Transition state - eclosion from pupa to adult-in-cocoon.
Complete pupal metamorphosis, creating overwintering adult.
Returns
Next state (st_Die as pupa deleted)
Eclosion sequence:
Create Osmia_InCocoon object (overwintering adult)
Transfer attributes including final adult mass (from provision mass conversion)
Update nest pointer
Delete pupa object
Adult-in-cocoon begins overwintering phase
Biological Transition
Adult bee emerges from pupal cuticle but remains within protective cocoon. Will not leave nest until spring emergence conditions are met (diapause completion + warming). This is key overwintering strategy - adults overwinter in cocoons rather than as pupae.
Creates a new Osmia_InCocoon object (pharate adult within cocoon) inheriting all state from the pupa, then removes the pupa object. Represents completion of metamorphosis but NOT emergence from the cocoon.
Returns
toOsmias_Emerged (return value not used as object is destroyed; nomenclature is historical)
Biological Context
Metamorphosis completion produces a fully formed adult within the cocoon. This pharate adult (Osmia_InCocoon) has completed tissue transformation but remains sealed within the cocoon, typically from late summer through winter until spring emergence. The pharate adult undergoes winter dormancy, accumulating overwintering degree-days that influence spring emergence timing and experiencing temperature-dependent winter mortality.
Critical Distinction
This method name (st_Emerge) is misleading nomenclature carried through the inheritance hierarchy. The pupa does not "emerge" from the cocoon; rather, it completes metamorphosis to become a pharate adult within the cocoon. True emergence (adult exit from cocoon) occurs months later in spring from the Osmia_InCocoon stage via its own st_Emerge() method.
State Transfer
All state transfers to the overwintering adult: body mass (determines adult quality), sex (determines whether to model the individual as females are modelled but males are not), parasitism status (may cause death at emergence), nest association, and age. The Osmia_InCocoon stage uses completely different developmental mechanisms (emergence counter, winter mortality) rather than continuing degree-day accumulation.
Model Outputs
Records pupal duration under OSMIATESTING for validation. Given the large calibration applied to pupal parameters, comparing simulated durations with field observations (when available) is important for model credibility.
See also
Osmia_InCocoon constructor for overwintering adult initialization
Osmia_InCocoon::st_Emerge() for actual emergence from cocoon in spring
struct_Osmia for state transfer data structure
Determines sex, and creates a new Osmia adult in cocoon object and passes the data from the pupa to it, then signals young object removal.
Reimplemented in Osmia_InCocoon.
Definition at line 2455 of file Osmia_dox.cpp.
References struct_Osmia::age, struct_Osmia::L, Osmia_Base::m_Age, Osmia_Base::m_Mass, Osmia_Base::m_OurNest, Osmia_Base::m_OurPopulationManager, Osmia_Base::m_ParasitoidStatus, Osmia_Egg::m_Sex, Osmia_Egg::m_StageAge, struct_Osmia::mass, struct_Osmia::nest, struct_Osmia::OPM, struct_Osmia::parasitised, struct_Osmia::sex, to_OsmiaInCocoon, toOsmias_Emerged, struct_Osmia::x, and struct_Osmia::y.
Referenced by Step().
Step()
void Osmia_Pupa::Step (void) virtual
Main step function.
Execute daily time step for pupa agent.
Implements state machine controlling pupal behaviour. Pupae call st_Develop() to accumulate degree-days through metamorphosis until completion, at which point transition to overwintering adult (Osmia_InCocoon) occurs.
State Machine Logic
toOsmias_InitialState: Entry point, transitions immediately to Develop
toOsmias_Develop: Accumulates degree-days through metamorphosis, checks mortality
toOsmias_NextStage: Triggers emergence via st_Emerge(), creating InCocoon object
toOsmias_Die: Executes death, removes from nest and simulation
Biological Context
During metamorphosis, larval tissues are broken down (except imaginal discs) and adult structures assembled. This profound transformation carries elevated mortality risk (0.3% daily). The timing of completion is critical: too early causes autumn emergence (fatal due to no floral resources), too late prevents appropriate overwintering. The calibrated developmental parameters ensure metamorphosis completes in late summer/autumn, leaving individuals as pharate adults for overwintering.
Comment on "Emerge" Terminology
The st_Emerge() method does not represent adult emergence from the cocoon but rather completion of metamorphosis. The pupa transforms into a pharate adult (Osmia_InCocoon) that remains within the cocoon through winter. True emergence (adult exit from cocoon) occurs much later from the Osmia_InCocoon stage in spring.
See also
st_Develop() for degree-day accumulation
st_Emerge() for transition to overwintering adult
Osmia pupa behaviour is simple. It calls develop until the pupa emerges or dies.
Reimplemented from Osmia_Prepupa.
Reimplemented in Osmia_InCocoon, and Osmia_Female.
Definition at line 2319 of file Osmia_dox.cpp.
References Osmia_Base::m_CurrentOState, st_Develop(), Osmia_Base::st_Dying(), st_Emerge(), toOsmias_Develop, toOsmias_Die, toOsmias_InitialState, and toOsmias_NextStage.
The documentation for this class was generated from the following files:
src/Osmia_enh_PART2_LifeStages.h
src/Osmia_dox.cpp
src/Osmia_enhanced.cpp