var searchData=
[
  ['paper_20publication_20sequence_0',['1.3 Three-Paper Publication Sequence',['../index.html#autotoc_md6',1,'']]],
  ['parallelization_20strategy_1',['3.3 Parallelization Strategy',['../index.html#autotoc_md29',1,'']]],
  ['parameter_20organization_2',['5.1 Parameter Organization',['../index.html#autotoc_md46',1,'']]],
  ['parameter_20sensitivity_20and_20uncertainty_20propagation_3',['5.8 Parameter Sensitivity and Uncertainty Propagation',['../index.html#autotoc_md53',1,'']]],
  ['parameterization_4',['8.3.3 Foraging Behaviour Parameterization',['../index.html#autotoc_md96',1,'']]],
  ['parameters_5',['Parameters',['../index.html#autotoc_md45',1,'5. Parameters'],['../index.html#autotoc_md47',1,'5.2 Development Parameters'],['../index.html#autotoc_md48',1,'5.3 Mortality Parameters'],['../index.html#autotoc_md49',1,'5.4 Provisioning and Reproduction Parameters'],['../index.html#autotoc_md50',1,'5.5 Spatial Parameters'],['../index.html#autotoc_md51',1,'5.6 Environmental Parameters'],['../index.html#autotoc_md52',1,'5.7 Parasitism Parameters']]],
  ['parasitism_6',['4.4 Parasitism',['../index.html#autotoc_md44',1,'']]],
  ['parasitism_20parameters_7',['5.7 Parasitism Parameters',['../index.html#autotoc_md52',1,'']]],
  ['phase_201_3a_20dofirst_20environmental_20updates_8',['Phase 1: DoFirst() - Environmental Updates',['../index.html#autotoc_md24',1,'']]],
  ['phase_202_3a_20individual_20beginstep_20agent_20pre_20processing_9',['Phase 2: Individual BeginStep() - Agent Pre-Processing',['../index.html#autotoc_md25',1,'']]],
  ['phase_203_3a_20individual_20step_20main_20agent_20actions_10',['Phase 3: Individual Step() - Main Agent Actions',['../index.html#autotoc_md26',1,'']]],
  ['phase_204_3a_20dolast_20end_20of_20day_20processing_11',['Phase 4: DoLast() - End-of-Day Processing',['../index.html#autotoc_md27',1,'']]],
  ['phenological_20metrics_12',['7.3.3 Phenological Metrics',['../index.html#autotoc_md79',1,'']]],
  ['pollen_20map_20format_13',['6.2.2 Pollen Map Format',['../index.html#autotoc_md63',1,'']]],
  ['pollen_20maps_20from_20field_20surveys_14',['6.3.1 Creating Pollen Maps from Field Surveys',['../index.html#autotoc_md65',1,'']]],
  ['polygon_20based_20landscape_20vs_20grid_15',['8.1.3 Polygon-Based Landscape vs. Grid',['../index.html#autotoc_md88',1,'']]],
  ['population_16',['6.1.4 Initial Population',['../index.html#autotoc_md60',1,'']]],
  ['population_20manager_17',['2.2.2 Population Manager',['../index.html#autotoc_md13',1,'']]],
  ['population_20model_3a_20midox_20implementation_20documentation_18',['&lt;em&gt;Osmia bicornis&lt;/em&gt; Population Model: MIDox Implementation Documentation',['../index.html',1,'']]],
  ['population_20time_20series_19',['7.1.1 Population Time Series',['../index.html#autotoc_md70',1,'']]],
  ['population_20viability_20',['7.3.1 Assessing Population Viability',['../index.html#autotoc_md77',1,'']]],
  ['portability_20and_20dependencies_21',['8.5.2 Portability and Dependencies',['../index.html#autotoc_md103',1,'']]],
  ['post_20processing_20and_20visualization_22',['7.4 Post-Processing and Visualization',['../index.html#autotoc_md80',1,'']]],
  ['practices_23',['8.5.1 Code Quality Practices',['../index.html#autotoc_md102',1,'']]],
  ['pre_20processing_24',['Phase 2: Individual BeginStep() - Agent Pre-Processing',['../index.html#autotoc_md25',1,'']]],
  ['preparation_20workflows_25',['6.3 Data Preparation Workflows',['../index.html#autotoc_md64',1,'']]],
  ['prepupal_20development_20modified_20approach_26',['4.1.2 Prepupal Development (Modified Approach)',['../index.html#autotoc_md34',1,'']]],
  ['prepupal_20development_3a_20the_20critical_20knowledge_20gap_27',['8.3.1 Prepupal Development: The Critical Knowledge Gap',['../index.html#autotoc_md94',1,'']]],
  ['principles_20and_20trade_20offs_28',['8.1 Design Principles and Trade-offs',['../index.html#autotoc_md85',1,'']]],
  ['priorities_29',['Priorities',['../index.html#autotoc_md93',1,'8.3 Major Uncertainties and Research Priorities'],['../index.html#autotoc_md97',1,'8.4 Future Development Priorities']]],
  ['processes_30',['Processes',['../index.html#autotoc_md19',1,'2.4.1 Core Processes'],['../index.html#autotoc_md36',1,'4.1.4 Mortality Processes'],['../index.html#autotoc_md41',1,'4.3 Spatial Processes']]],
  ['processes_20and_20emergent_20properties_31',['2.4 Key Processes and Emergent Properties',['../index.html#autotoc_md18',1,'']]],
  ['processing_32',['Processing',['../index.html#autotoc_md25',1,'Phase 2: Individual BeginStep() - Agent Pre-Processing'],['../index.html#autotoc_md27',1,'Phase 4: DoLast() - End-of-Day Processing']]],
  ['processing_20and_20visualization_33',['7.4 Post-Processing and Visualization',['../index.html#autotoc_md80',1,'']]],
  ['processing_20weather_20station_20data_34',['6.3.2 Processing Weather Station Data',['../index.html#autotoc_md66',1,'']]],
  ['propagation_35',['5.8 Parameter Sensitivity and Uncertainty Propagation',['../index.html#autotoc_md53',1,'']]],
  ['properties_36',['Properties',['../index.html#autotoc_md18',1,'2.4 Key Processes and Emergent Properties'],['../index.html#autotoc_md20',1,'2.4.2 Emergent Properties']]],
  ['provisioning_20and_20reproduction_20parameters_37',['5.4 Provisioning and Reproduction Parameters',['../index.html#autotoc_md49',1,'']]],
  ['provisioning_20behaviour_38',['4.2 Female Provisioning Behaviour',['../index.html#autotoc_md37',1,'']]],
  ['provisioning_20dynamics_39',['4.2.2 Provisioning Dynamics',['../index.html#autotoc_md39',1,'']]],
  ['publication_20sequence_40',['1.3 Three-Paper Publication Sequence',['../index.html#autotoc_md6',1,'']]],
  ['purpose_20and_20scope_41',['2.1 Model Purpose and Scope',['../index.html#autotoc_md10',1,'']]]
];
