Osmia bicornis Population Model: src/Osmia_dox.cpp File Reference
Osmia_dox.cpp File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <random>
#include "../BatchALMaSS/ALMaSS_Setup.h"
#include "../ALMaSSDefines.h"
#include "../Landscape/ls.h"
#include "../BatchALMaSS/ALMaSS_Random.h"
#include "../BatchALMaSS/PopulationManager.h"
#include "../Osmia/Osmia.h"
#include "../Osmia/Osmia_Population_Manager.h"
Functions
static CfgFloat cfg_OsmiaEggDevelTotalDD ("OSMIA_EGGDEVELDD", CFG_CUSTOM, 86.0)
static CfgFloat cfg_OsmiaEggDevelThreshold ("OSMIA_EGGDEVELTHRESHOLD", CFG_CUSTOM, 0.0)
static CfgFloat cfg_OsmiaLarvaDevelTotalDD ("OSMIA_LARVADEVELDD", CFG_CUSTOM, 422)
static CfgFloat cfg_OsmiaLarvaDevelThreshold ("OSMIA_LARVADEVELTHRESHOLD", CFG_CUSTOM, 4.5)
static CfgFloat cfg_OsmiaPupaDevelTotalDD ("OSMIA_PUPADEVELDD", CFG_CUSTOM, 570)
static CfgFloat cfg_OsmiaPupaDevelThreshold ("OSMIA_PUPADEVELTHRESHOLD", CFG_CUSTOM, 1.1)
CfgFloat cfg_OsmiaInCocoonOverwinteringTempThreshold ("OSMIA_INCOCOONOVERWINTERINGTEMPTHRESHOLD", CFG_CUSTOM, 0.0)
CfgFloat cfg_OsmiaInCocoonEmergenceTempThreshold ("OSMIA_INCOCOONEMERGENCETEMPTHRESHOLD", CFG_CUSTOM, 5.0)
CfgFloat cfg_OsmiaInCocoonPrewinteringTempThreshold ("OSMIA_INCOCOONPREWINTERINGTEMPTHRESHOLD", CFG_CUSTOM, 15.0)
static CfgFloat cfg_OsmiaPrepupaDevelTotalDays ("OSMIA_PREPUPADEVELDAYS", CFG_CUSTOM, 45)
CfgFloat cfg_OsmiaInCocoonEmergCountConst ("OSMIA_INCOCOONEMERGENCECOUNTERCONST", CFG_CUSTOM, 35.4819)
CfgFloat cfg_OsmiaInCocoonEmergCountSlope ("OSMIA_INCOCOONEMERGENCECOUNTERSLOPE", CFG_CUSTOM, -0.0147)
static CfgFloat cfg_OsmiaEggDailyMORT ("OSMIA_EGGDAILYMORT", CFG_CUSTOM, 0.0014)
static CfgFloat cfg_OsmiaLarvaDailyMORT ("OSMIA_LARVADAILYMORT", CFG_CUSTOM, 0.0014)
static CfgFloat cfg_OsmiaPrepupaDailyMORT ("OSMIA_PREPUPADAILYMORT", CFG_CUSTOM, 0.003)
static CfgFloat cfg_OsmiaPupaDailyMORT ("OSMIA_PUPADAILYMORT", CFG_CUSTOM, 0.003)
CfgFloat cfg_OsmiaInCocoonWinterMortConst ("OSMIA_INCOCOONWINTERMORTCONST", CFG_CUSTOM, -4.63)
CfgFloat cfg_OsmiaInCocoonWinterMortSlope ("OSMIA_INCOCOONWINTERMORTSLOPE", CFG_CUSTOM, 0.05)
CfgFloat cfg_OsmiaMaleMassMin ("OSMIA_MINMALEMASS", CFG_CUSTOM, 88)
CfgFloat cfg_OsmiaMaleMassMax ("OSMIA_MAXMALEMASS", CFG_CUSTOM, 105.0)
CfgFloat cfg_OsmiaFemaleMassMin ("OSMIA_MINFEMALEMASS", CFG_CUSTOM, 25.0)
CfgFloat cfg_OsmiaFemaleMassMax ("OSMIA_MAXFEMALEMASS", CFG_CUSTOM, 200.0)
CfgInt cfg_OsmiaFemalePrenestingDuration ("OSMIA_PRENESTINGDURATION", CFG_CUSTOM, 2)
CfgInt cfg_OsmiaFemaleLifespan ("OSMIA_LIFESPAN", CFG_CUSTOM, 60)
CfgFloat cfg_OsmiaFemaleMassFromProvMassConst ("OSMIA_FEMALEMASSFROMPROVMASSCONST", CFG_CUSTOM, 4.00)
CfgFloat cfg_OsmiaFemaleMassFromProvMassSlope ("OSMIA_FEMALEMASSFROMPROVMASSSLOPE", CFG_CUSTOM, 0.25)
CfgFloat cfg_OsmiaInsecticideApplicationMortality ("OSMIA_INSECTICIDE_APPLICATION_MORTALITY", CFG_CUSTOM, 0.8)
CfgInt cfg_OsmiaDetailedMaskStep ("OSMIA_DETAILEDMASKSTEP", CFG_CUSTOM, 1, 1, 100)
static CfgStr cfg_OsmiaDispersalMovementProbType ("OSMIA_DISPMOVPROBTYPE", CFG_CUSTOM, "BETA")
static CfgStr cfg_OsmiaDispersalMovementProbArgs ("OSMIA_DISPMOVPROBARGS", CFG_CUSTOM, "10 5")
static CfgStr cfg_OsmiaGeneralMovementProbType ("OSMIA_GENMOVPROBTYPE", CFG_CUSTOM, "BETA")
static CfgStr cfg_OsmiaGenerallMovementProbArgs ("OSMIA_GENMOVPROBARGS", CFG_CUSTOM, "10 5")
static CfgStr cfg_OsmiaEggsPerNestProbType ("OSMIA_EGGSPERNESTPROBYPE", CFG_CUSTOM, "BETA")
static CfgStr cfg_OsmiaEggsPerNestProbArgs ("OSMIA_EGGSPERNESTPROBARGS", CFG_CUSTOM, "1.0 4.00")
static CfgStr cfg_OsmiaEmergenceProbType ("OSMIA_EMERGENCEPROBTYPE", CFG_CUSTOM, "DISCRETE")
static CfgStr cfg_OsmiaEmergenceProbArgs ("OSMIA_EMERGENCEPROBARGS", CFG_CUSTOM, "8 7 9 24 20 8 6 5 5 4 4")
CfgInt cfg_OsmiaForageSteps ("OSMIA_FORAGESTEPS", CFG_CUSTOM, 20)
static CfgInt cfg_OsmiaForageMaskStepSZ ("OSMIA_FORAGEMASKSTEPSZ", CFG_CUSTOM, cfg_OsmiaTypicalHomingDistance.value()/(cfg_OsmiaForageSteps.value() - 1))
static CfgFloat cfg_OsmiaMaxPollen ("OSMIA_MAXPOLLEN", CFG_CUSTOM, 2.5)
static CfgFloat cfg_OsmiaSugarPerDay ("OSMIA_NECTAR_PER_DAY", CFG_CUSTOM, 20)
CfgInt cfg_OsmiaMaxHalfWidthForageMask ("OSMIA_MAX_HALF_WIDTH_FORAGE_MASK", CFG_CUSTOM, 600)
CfgInt cfg_OsmiaForageMaskStep ("OSMIA_FORAGE_MASK_STEP", CFG_CUSTOM, 50)
CfgBool cfg_OsmiaFemaleThresholdBasedPesticideResponse ("OSMIA_FEMALE_THRESHOLD_BASED_PESTICIDE_RESPONSE", CFG_CUSTOM, true)
CfgBool cfg_OsmiaFemaleDamageBasedPesticideResponse ("OSMIA_FEMALE_DAMAGE_BASED_PESTICIDE_RESPONSE", CFG_CUSTOM, false)
CfgBool cfg_OsmiaEggThresholdBasedPesticideResponse ("OSMIA_EGG_THRESHOLD_BASED_PESTICIDE_RESPONSE", CFG_CUSTOM, true)
static std::uniform_int_distribution< int > g_uni_0to15 (0, 35)
Variables
MapErrorMsg * g_msg
CfgFloat cfg_OsmiaAdultMassCategoryStep
Step size for discretizing adult female mass into categories.
CfgFloat cfg_OsmiaCocoonMassFromProvMass
CfgFloat cfg_OsmiaProvMassFromCocoonMass
Bidirectional conversion factors: cocoon mass ↔ provision mass.
CfgInt l_pest_NoPPPs
CfgFloat cfg_biocide_reduction_val
std::mt19937 g_generator
Function Documentation
cfg_OsmiaDetailedMaskStep()
CfgInt cfg_OsmiaDetailedMaskStep ("OSMIA_DETAILEDMASKSTEP" , CFG_CUSTOM , 1 , 1 , 100)
cfg_OsmiaDispersalMovementProbArgs()
CfgStr cfg_OsmiaDispersalMovementProbArgs ("OSMIA_DISPMOVPROBARGS" , CFG_CUSTOM , "10 5") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaDispersalMovementProbType()
CfgStr cfg_OsmiaDispersalMovementProbType ("OSMIA_DISPMOVPROBTYPE" , CFG_CUSTOM , "BETA") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaEggDailyMORT()
CfgFloat cfg_OsmiaEggDailyMORT ("OSMIA_EGGDAILYMORT" , CFG_CUSTOM , 0. 0014) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaEggDevelThreshold()
CfgFloat cfg_OsmiaEggDevelThreshold ("OSMIA_EGGDEVELTHRESHOLD" , CFG_CUSTOM , 0. 0) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaEggDevelTotalDD()
CfgFloat cfg_OsmiaEggDevelTotalDD ("OSMIA_EGGDEVELDD" , CFG_CUSTOM , 86. 0) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaEggsPerNestProbArgs()
CfgStr cfg_OsmiaEggsPerNestProbArgs ("OSMIA_EGGSPERNESTPROBARGS" , CFG_CUSTOM , "1.0 4.00") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaEggsPerNestProbType()
CfgStr cfg_OsmiaEggsPerNestProbType ("OSMIA_EGGSPERNESTPROBYPE" , CFG_CUSTOM , "BETA") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaEggThresholdBasedPesticideResponse()
CfgBool cfg_OsmiaEggThresholdBasedPesticideResponse ("OSMIA_EGG_THRESHOLD_BASED_PESTICIDE_RESPONSE" , CFG_CUSTOM , true)
Referenced by Osmia_Egg::st_Develop().
cfg_OsmiaEmergenceProbArgs()
CfgStr cfg_OsmiaEmergenceProbArgs ("OSMIA_EMERGENCEPROBARGS" , CFG_CUSTOM , "8 7 9 24 20 8 6 5 5 4 4") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaEmergenceProbType()
CfgStr cfg_OsmiaEmergenceProbType ("OSMIA_EMERGENCEPROBTYPE" , CFG_CUSTOM , "DISCRETE") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaFemaleDamageBasedPesticideResponse()
CfgBool cfg_OsmiaFemaleDamageBasedPesticideResponse ("OSMIA_FEMALE_DAMAGE_BASED_PESTICIDE_RESPONSE" , CFG_CUSTOM , false)
cfg_OsmiaFemaleLifespan()
CfgInt cfg_OsmiaFemaleLifespan ("OSMIA_LIFESPAN" , CFG_CUSTOM , 60)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaFemaleMassFromProvMassConst()
CfgFloat cfg_OsmiaFemaleMassFromProvMassConst ("OSMIA_FEMALEMASSFROMPROVMASSCONST" , CFG_CUSTOM , 4. 00)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaFemaleMassFromProvMassSlope()
CfgFloat cfg_OsmiaFemaleMassFromProvMassSlope ("OSMIA_FEMALEMASSFROMPROVMASSSLOPE" , CFG_CUSTOM , 0. 25)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaFemaleMassMax()
CfgFloat cfg_OsmiaFemaleMassMax ("OSMIA_MAXFEMALEMASS" , CFG_CUSTOM , 200. 0)
cfg_OsmiaFemaleMassMin()
CfgFloat cfg_OsmiaFemaleMassMin ("OSMIA_MINFEMALEMASS" , CFG_CUSTOM , 25. 0)
cfg_OsmiaFemalePrenestingDuration()
CfgInt cfg_OsmiaFemalePrenestingDuration ("OSMIA_PRENESTINGDURATION" , CFG_CUSTOM , 2)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaFemaleThresholdBasedPesticideResponse()
CfgBool cfg_OsmiaFemaleThresholdBasedPesticideResponse ("OSMIA_FEMALE_THRESHOLD_BASED_PESTICIDE_RESPONSE" , CFG_CUSTOM , true)
cfg_OsmiaForageMaskStep()
CfgInt cfg_OsmiaForageMaskStep ("OSMIA_FORAGE_MASK_STEP" , CFG_CUSTOM , 50)
cfg_OsmiaForageMaskStepSZ()
CfgInt cfg_OsmiaForageMaskStepSZ ("OSMIA_FORAGEMASKSTEPSZ" , CFG_CUSTOM , cfg_OsmiaTypicalHomingDistance. value)/(cfg_OsmiaForageSteps.value() - 1) static
References cfg_OsmiaForageSteps, and cfg_OsmiaTypicalHomingDistance.
cfg_OsmiaForageSteps()
CfgInt cfg_OsmiaForageSteps ("OSMIA_FORAGESTEPS" , CFG_CUSTOM , 20)
cfg_OsmiaGenerallMovementProbArgs()
CfgStr cfg_OsmiaGenerallMovementProbArgs ("OSMIA_GENMOVPROBARGS" , CFG_CUSTOM , "10 5") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaGeneralMovementProbType()
CfgStr cfg_OsmiaGeneralMovementProbType ("OSMIA_GENMOVPROBTYPE" , CFG_CUSTOM , "BETA") static
Referenced by cfg_OsmiaSugarPerDay(), and cfg_OsmiaSugarPerDay().
cfg_OsmiaInCocoonEmergCountConst()
CfgFloat cfg_OsmiaInCocoonEmergCountConst ("OSMIA_INCOCOONEMERGENCECOUNTERCONST" , CFG_CUSTOM , 35. 4819)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaInCocoonEmergCountSlope()
CfgFloat cfg_OsmiaInCocoonEmergCountSlope ("OSMIA_INCOCOONEMERGENCECOUNTERSLOPE" , CFG_CUSTOM , -0. 0147)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaInCocoonEmergenceTempThreshold()
CfgFloat cfg_OsmiaInCocoonEmergenceTempThreshold ("OSMIA_INCOCOONEMERGENCETEMPTHRESHOLD" , CFG_CUSTOM , 5. 0)
cfg_OsmiaInCocoonOverwinteringTempThreshold()
CfgFloat cfg_OsmiaInCocoonOverwinteringTempThreshold ("OSMIA_INCOCOONOVERWINTERINGTEMPTHRESHOLD" , CFG_CUSTOM , 0. 0)
cfg_OsmiaInCocoonPrewinteringTempThreshold()
CfgFloat cfg_OsmiaInCocoonPrewinteringTempThreshold ("OSMIA_INCOCOONPREWINTERINGTEMPTHRESHOLD" , CFG_CUSTOM , 15. 0)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaInCocoonWinterMortConst()
CfgFloat cfg_OsmiaInCocoonWinterMortConst ("OSMIA_INCOCOONWINTERMORTCONST" , CFG_CUSTOM , -4. 63)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaInCocoonWinterMortSlope()
CfgFloat cfg_OsmiaInCocoonWinterMortSlope ("OSMIA_INCOCOONWINTERMORTSLOPE" , CFG_CUSTOM , 0. 05)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaInsecticideApplicationMortality()
CfgFloat cfg_OsmiaInsecticideApplicationMortality ("OSMIA_INSECTICIDE_APPLICATION_MORTALITY" , CFG_CUSTOM , 0. 8)
References cfg_biocide_reduction_val.
cfg_OsmiaLarvaDailyMORT()
CfgFloat cfg_OsmiaLarvaDailyMORT ("OSMIA_LARVADAILYMORT" , CFG_CUSTOM , 0. 0014) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaLarvaDevelThreshold()
CfgFloat cfg_OsmiaLarvaDevelThreshold ("OSMIA_LARVADEVELTHRESHOLD" , CFG_CUSTOM , 4. 5) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaLarvaDevelTotalDD()
CfgFloat cfg_OsmiaLarvaDevelTotalDD ("OSMIA_LARVADEVELDD" , CFG_CUSTOM , 422) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaMaleMassMax()
CfgFloat cfg_OsmiaMaleMassMax ("OSMIA_MAXMALEMASS" , CFG_CUSTOM , 105. 0)
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaMaleMassMin()
CfgFloat cfg_OsmiaMaleMassMin ("OSMIA_MINMALEMASS" , CFG_CUSTOM , 88)
cfg_OsmiaMaxHalfWidthForageMask()
CfgInt cfg_OsmiaMaxHalfWidthForageMask ("OSMIA_MAX_HALF_WIDTH_FORAGE_MASK" , CFG_CUSTOM , 600)
cfg_OsmiaMaxPollen()
CfgFloat cfg_OsmiaMaxPollen ("OSMIA_MAXPOLLEN" , CFG_CUSTOM , 2. 5) static
cfg_OsmiaPrepupaDailyMORT()
CfgFloat cfg_OsmiaPrepupaDailyMORT ("OSMIA_PREPUPADAILYMORT" , CFG_CUSTOM , 0. 003) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaPrepupaDevelTotalDays()
CfgFloat cfg_OsmiaPrepupaDevelTotalDays ("OSMIA_PREPUPADEVELDAYS" , CFG_CUSTOM , 45) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaPupaDailyMORT()
CfgFloat cfg_OsmiaPupaDailyMORT ("OSMIA_PUPADAILYMORT" , CFG_CUSTOM , 0. 003) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaPupaDevelThreshold()
CfgFloat cfg_OsmiaPupaDevelThreshold ("OSMIA_PUPADEVELTHRESHOLD" , CFG_CUSTOM , 1. 1) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaPupaDevelTotalDD()
CfgFloat cfg_OsmiaPupaDevelTotalDD ("OSMIA_PUPADEVELDD" , CFG_CUSTOM , 570) static
Referenced by Osmia_Base::SetParameterValues().
cfg_OsmiaSugarPerDay()
CfgFloat cfg_OsmiaSugarPerDay ("OSMIA_NECTAR_PER_DAY" , CFG_CUSTOM , 20) static
References cfg_OsmiaDispersalMovementProbArgs(), cfg_OsmiaDispersalMovementProbType(), cfg_OsmiaEggsPerNestProbArgs(), cfg_OsmiaEggsPerNestProbType(), cfg_OsmiaEmergenceProbArgs(), cfg_OsmiaEmergenceProbType(), cfg_OsmiaGenerallMovementProbArgs(), cfg_OsmiaGeneralMovementProbType(), Osmia_Base::m_dispersalmovementdistances, Osmia_Base::m_eggspernestdistribution, Osmia_Base::m_emergenceday, Osmia_Base::m_exp_ZeroToOne, and Osmia_Base::m_generalmovementdistances.
g_uni_0to15()
std::uniform_int_distribution< int > g_uni_0to15 (0 , 35) static
References g_generator.
Variable Documentation
cfg_biocide_reduction_val
CfgFloat cfg_biocide_reduction_val extern
Referenced by cfg_OsmiaInsecticideApplicationMortality().
cfg_OsmiaAdultMassCategoryStep
CfgFloat cfg_OsmiaAdultMassCategoryStep extern
Step size for discretizing adult female mass into categories.
Adult females binned into mass categories for lookup table indexing. Category = (mass - 4.0) / step_size. Default step 10.0 mg creates coarse categories (insufficient resolution for realistic size-dependent behaviour).
Implementation Note
Despite configuration variable existing, actual implementation uses fixed 0.25 mg step (see Init() code). This finer resolution (96 categories spanning 4-28 mg range) necessary for accurate representation of mass-dependent sex ratios and provisioning targets observed by Seidelmann et al. (2010).
Biological Context
Female body mass critical trait affecting:
Fecundity (larger females lay more eggs)
Provisioning strategy (larger females invest more per offspring)
Sex ratio (larger females produce more female-biased broods)
Survival (larger females may have lower mortality)
Coarse mass categories (10 mg steps) obscure these patterns. Fine categories (0.25 mg) capture observed variation whilst remaining computationally tractable.
Difference from Config
CONFIG VALUE NOT ACTUALLY USED - Code uses hardcoded 0.25 mg step regardless of configuration value. This discrepancy should be resolved by either:
Removing configuration variable (acknowledging fixed design choice)
Implementing configuration-driven step size (requires validating lookup tables)
Current state represents development artifact where initial design (coarse categories) replaced by finer resolution after discovering importance of size variation, but configuration variable not updated.
cfg_OsmiaCocoonMassFromProvMass
CfgFloat cfg_OsmiaCocoonMassFromProvMass extern
cfg_OsmiaProvMassFromCocoonMass
CfgFloat cfg_OsmiaProvMassFromCocoonMass extern
Bidirectional conversion factors: cocoon mass ↔ provision mass.
Linear relationships derived from Seidelmann (2006):
Cocoon mass = provision mass / 3.247
Provision mass = cocoon mass × 3.247
Biological Interpretation
Not all provision (pollen + nectar) converts to cocoon (larval body). Losses from:
Metabolism during development (~40% of consumed energy)
Waste products (frass, uric acid)
Water loss during cocoon construction
Unconsumed provision remnants
Factor 3.247 means ~31% conversion efficiency (1/3.247 ≈ 0.31), consistent with insect development energetics.
Difference from Formal Model
EXACT MATCH - Seidelmann (2006) conversion factors implemented precisely.
Data Source
Laboratory measurements: weigh provision before larva feeds, weigh cocoon after spinning. Regression provides conversion. High confidence because direct measurement.
g_generator
std::mt19937 g_generator extern
Referenced by g_uni_0to15(), and g_uni_0to15().
g_msg
MapErrorMsg* g_msg extern
l_pest_NoPPPs
CfgInt l_pest_NoPPPs extern