Osmia bicornis Population Model: Osmia_Larva Class Reference
Osmia_Larva Class Reference
Feeding larval stage consuming provision mass.
#include <Osmia_enh_PART2_LifeStages.h>
Public Member Functions
Osmia_Larva (struct_Osmia *data)
Constructor for new larva (created during egg hatching).
virtual void ReInit (struct_Osmia *data)
Reinitialize larva object from object pool.
virtual ~Osmia_Larva ()
Destructor.
virtual void Step (void)
Main step function executing larval behaviour.
Public Member Functions inherited from Osmia_Egg
Osmia_Egg (struct_Osmia *data)
Constructor for new egg object.
virtual ~Osmia_Egg ()
Destructor.
double GetAgeDegrees ()
Get accumulated degree-days.
void SetAgeDegrees (unsigned a_agedegrees)
Set accumulated degree-days (used during object reinitialization).
Public Member Functions inherited from Osmia_Base
Osmia_Base (struct_Osmia *data)
Constructor creating new Osmia_Base individual.
void ReInit (struct_Osmia *data)
Reinitialize object from object pool.
virtual ~Osmia_Base ()
Virtual destructor ensuring proper cleanup in derived classes.
virtual void st_Dying (void)
Behavioural state for death - cleanup and removal.
virtual void BeginStep (void)
First phase of daily timestep.
virtual void EndStep (void)
Final phase of daily timestep.
int GetAge ()
Get individual's age in days.
void SetAge (int a_age)
Set individual's age in days.
double GetMass ()
Get individual's mass (mg) - interpretation depends on life stage.
void SetMass (double a_mass)
Set individual's mass (mg).
void SetParasitised (TTypeOfOsmiaParasitoids a_status)
Set parasitism status.
TTypeOfOsmiaParasitoids GetParasitised (void)
Get parasitism status.
Osmia_Nest * GetNest ()
Get pointer to nest containing or being provisioned by this individual.
Protected Member Functions
virtual TTypeOfOsmiaState st_Develop (void)
Development state - accumulate degree-days toward prepupation.
virtual TTypeOfOsmiaState st_Prepupate (void)
Transition state - metamorphose from larva to prepupa.
virtual bool DailyMortality ()
Daily mortality test for larvae.
Protected Member Functions inherited from Osmia_Egg
virtual TTypeOfOsmiaState st_Hatch (void)
Transition state - metamorphose from egg to larva.
Additional Inherited Members
Static Public Member Functions inherited from Osmia_Base
static void SetParameterValues ()
Populate all static parameters from configuration file.
static void SetTemp (double a_temperature)
Set current daily temperature for all individuals.
static void SetParasitoidManager (OsmiaParasitoid_Population_Manager *a_popman)
Set parasitoid population manager pointer.
Protected Attributes inherited from Osmia_Egg
double m_AgeDegrees = 0.0
Accumulated degree-days toward hatching threshold.
bool m_Sex
Sex of individual (true = female = fertilised egg).
int m_StageAge
Age in days when current life stage was entered.
double m_egg_pest_mortality
Cumulative pesticide mortality probability for this egg.
Protected Attributes inherited from Osmia_Base
TTypeOfOsmiaState m_CurrentOState
Current behavioural state governing agent decisions.
int m_Age
Chronological age in days since egg laying.
Osmia_Population_Manager * m_OurPopulationManager
Pointer to the Osmia population manager instance.
TTypeOfOsmiaParasitoids m_ParasitoidStatus
Records parasitism status of this individual.
Osmia_Nest * m_OurNest
Pointer to nest containing this individual.
double m_Mass
Mass of individual or provision (mg) - interpretation varies by life stage.
int m_foragehours
Hours available for foraging today (decremented as foraging proceeds).
Static Protected Attributes inherited from Osmia_Base
static OsmiaParasitoid_Population_Manager * m_OurParasitoidPopulationManager = NULL
Static pointer to parasitoid population manager (if using mechanistic parasitoid model).
static double m_TempToday = -9999
Mean daily temperature (°C) for current timestep.
static int m_TempTodayInt = -9999
Rounded integer temperature for array indexing.
static double m_DailyDevelopmentMortEggs = 0
Daily mortality probability for eggs (probability per day).
static double m_DailyDevelopmentMortLarvae = 0
Daily mortality probability for larvae (probability per day).
static double m_DailyDevelopmentMortPrepupae = 0
Daily mortality probability for prepupae (probability per day).
static double m_DailyDevelopmentMortPupae = 0
Daily mortality probability for pupae (probability per day).
static double m_OsmiaEggDevelTotalDD = 0
Total degree-days required for egg development to hatching.
static double m_OsmiaEggDevelThreshold = 0
Lower developmental threshold temperature for eggs (°C).
static double m_OsmiaLarvaDevelTotalDD = 0
Total degree-days required for larval development to prepupal stage.
static double m_OsmiaLarvaDevelThreshold = 0
Lower developmental threshold temperature for larvae (°C).
static double m_OsmiaPupaDevelTotalDD = 0
Total degree-days required for pupal development to adult eclosion.
static double m_OsmiaPupaDevelThreshold = 0
Lower developmental threshold temperature for pupae (°C).
static double m_OsmiaPrepupalDevelTotalDays = 0
Total days for prepupal development at optimal temperature.
static double m_OsmiaPrepupalDevelTotalDays10pct = 0
Pre-computed 10% of prepupal development time.
static double m_OsmiaInCocoonOverwinteringTempThreshold = 0
Temperature threshold (°C) for accumulating overwintering degree-days.
static double m_OsmiaInCocoonEmergenceTempThreshold = 0
Temperature threshold (°C) for post-diapause emergence counter.
static double m_OsmiaInCocoonPrewinteringTempThreshold = 0
Temperature threshold (°C) for accumulating prewintering degree-days.
static double m_OsmiaInCocoonWinterMortConst = 0.0
Intercept for overwintering mortality equation.
static double m_OsmiaInCocoonWinterMortSlope = 0.0
Slope for overwintering mortality equation.
static double m_OsmiaInCocoonEmergCountConst = 0.0
Intercept for emergence counter equation.
static double m_OsmiaInCocoonEmergCountSlope = 0.0
Slope for emergence counter equation.
static double m_OsmiaFemaleMassFromProvMassConst = 0.0
Intercept for calculating female mass from provision mass.
static double m_OsmiaFemaleMassFromProvMassSlope = 0.0
Slope for calculating female mass from provision mass.
static double m_MaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for male nest cells (mg).
static double m_MaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for male nest cells (mg).
static double m_FemaleMinTargetProvisionMass = 0.0
Minimum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxTargetProvisionMass = 0.0
Maximum target provisioning mass for female nest cells (mg).
static double m_FemaleMaxMass = 0.0
Maximum female adult mass (mg) - sets upper bound for provision mass calculations.
static double m_FemaleMinMass = 0.0
Minimum female adult mass (mg) - sets lower bound for provision mass calculations.
static double m_MaleMaxMass = 0.0
Maximum male adult mass (mg) - males are smaller than females.
static double m_PollenScoreToMg = 0.0
Conversion factor from pollen availability score to provisioned mass (mg pollen per day).
static double m_DensityDependentPollenRemovalConst = 0.0
Parameter linking pollen depletion to Osmia population density.
static double m_MinimumCellConstructionTime = 0.0
Minimum time (days) required to construct and provision one nest cell.
static double m_MaximumCellConstructionTime = 0.0
Maximum time (days) required to construct and provision one nest cell.
static int m_TotalNestsPossible = 0
Maximum number of nests a female can complete in her lifetime.
static double m_BombylidProbability = 0.0
Baseline probability of bombyliid fly parasitism per open nest cell.
static double m_ParasitismProbToTimeCellOpen = 0.0
Conversion factor relating cell open time (days) to parasitism probability.
static vector< double > m_ParasitoidAttackChance = {}
Per-capita parasitoid attack probabilities for mechanistic parasitoid model.
static double m_OsmiaFemaleR50distance = 0.0
Typical homing distance - distance at which 50% of females cannot return to nest (m).
static double m_OsmiaFemaleR90distance = 0.0
Maximum homing distance - distance at which 90% of females cannot return (m).
static int m_OsmiaFemalePrenesting = 0
Duration of prenesting period after emergence (days).
static int m_OsmiaFemaleLifespan = 0
Maximum adult female lifespan (days).
static probability_distribution m_generalmovementdistances = probability_distribution(cfg_OsmiaGeneralMovementProbType.value(), cfg_OsmiaGenerallMovementProbArgs.value())
Probability distribution for foraging and nest-searching movements.
static probability_distribution m_dispersalmovementdistances = probability_distribution(cfg_OsmiaDispersalMovementProbType.value(), cfg_OsmiaDispersalMovementProbArgs.value())
Probability distribution for dispersal movements (longer than foraging movements).
static probability_distribution m_eggspernestdistribution = probability_distribution(cfg_OsmiaEggsPerNestProbType.value(), cfg_OsmiaEggsPerNestProbArgs.value())
Probability distribution for planned eggs per nest.
static probability_distribution m_exp_ZeroToOne = probability_distribution("BETA", "1.0, 5.0")
Exponential-like probability distribution over range [0,1].
static double m_CocoonToProvisionMass = 0.0
Mass conversion ratio from cocoon mass to provision mass required.
static double m_ProvisionToCocoonMass = 0.0
Mass conversion ratio from provision mass to resulting cocoon mass.
static double m_TotalProvisioningMassLoss = 0.0
Total provision mass loss from first to last egg in a nest (mg).
static double m_TotalProvisioningMassLossRange = 0.0
Stochastic range around total provisioning mass loss (mg).
static double m_TotalProvisioningMassLossRangeX2 = 0.0
Pre-computed double of mass loss range for efficiency.
static bool m_UsingMechanisticParasitoids = false
Flag selecting parasitism model: true=mechanistic population model, false=simple probabilities.
static double m_OsmiaFemaleBckMort = 0.0
Daily background mortality for adult females outside nest (probability per day).
static int m_OsmiaFemaleMinEggsPerNest = 0
Minimum eggs planned per nest (sets lower bound for egg planning distribution).
static int m_OsmiaFindNestAttemptNo = 0
Number of attempts allowed for finding suitable nest location before giving up.
static int m_OsmiaFemaleMaxEggsPerNest = 0
Maximum eggs planned per nest (sets upper bound for egg planning distribution).
static probability_distribution m_emergenceday = probability_distribution(cfg_OsmiaEmergenceProbType.value(), cfg_OsmiaEmergenceProbArgs.value())
Probability distribution for day of emergence relative to population mean.
Detailed Description
Feeding larval stage consuming provision mass.
Osmia_Larva represents the actively feeding larval stage from hatching through cocoon spinning. Larvae consume the provision mass left by their mother, growing through multiple instars before entering the prepupal stage. Development continues via degree-day accumulation with temperature threshold and requirements distinct from egg stage.
Biological Foundation
O. bicornis larvae progress through approximately 4-5 instars, consuming the entire provision mass over 3-4 weeks (temperature dependent). Larvae are relatively sedentary within their sealed cells, protected from most environmental hazards. Provision quality (pollen source diversity, nutrient content) affects larval growth and survival, though this is not explicitly modelled beyond mass effects.
Development Model
Continues degree-day accumulation from egg stage: m_AgeDegrees carries forward and increments by (T - T_larva_threshold) each day. When m_AgeDegrees reaches m_OsmiaEggDevelTotalDD + m_OsmiaLarvaDevelTotalDD, larva spins cocoon and transitions to prepupal stage.
Mass and Provisioning
Larval mass (m_Mass) represents the provision mass available in cell, set when egg was provisioned. This determines final adult size via conversion equation. Larvae don't actively "eat" provision (no depletion simulation) - mass is simply carried through as determinant of adult size.
Difference from Formal Model
Larval development threshold calibrated from 8.5°C to 4.5°C (see Osmia_Base). Mortality matches formal model exactly. The simplified mass handling (no explicit feeding simulation) is consistent with formal model's focus on outcome (adult mass) rather than process (feeding dynamics).
See also
Osmia_Base for larval development parameters
st_Develop() for development logic
st_Prepupate() for transition to prepupal stage
Definition at line 218 of file Osmia_enh_PART2_LifeStages.h.
Constructor & Destructor Documentation
Osmia_Larva()
Osmia_Larva::Osmia_Larva (struct_Osmia * data)
Constructor for new larva (created during egg hatching).
Constructor for Osmia_Larva from initialization data.
Parameters
data Initialization data transferred from egg plus larval-specific attributes
Inherits m_AgeDegrees from egg, increments m_StageAge to record larval entry, maintains sex, mass, and nest linkage. Ready to continue degree-day accumulation toward prepupal threshold.
Creates a new larva agent, typically from egg hatching but also supports direct creation for population initialization scenarios.
Parameters
data Pointer to struct_Osmia containing initialization data
Biological Context
Larvae are feeding stages that consume the pollen-nectar provision mass accumulated by their mother. Development proceeds through five larval instars, with body mass increasing and provision mass decreasing. Larval development duration and final body mass are critical determinants of adult fitness.
Implementation Notes
Inherits from Osmia_Egg, sharing the degree-day accumulation mechanism but with different parameters. The inheritance structure reflects biological continuity: larvae are essentially hatched eggs that continue degree-day based development.
See also
Osmia_Egg for inherited functionality
Definition at line 1840 of file Osmia_dox.cpp.
References Osmia_Egg::Osmia_Egg(), and ReInit().
Referenced by Osmia_Prepupa::Osmia_Prepupa().
~Osmia_Larva()
Osmia_Larva::~Osmia_Larva (void) virtual
Destructor.
Destructor for Osmia_Larva.
Empty destructor as cleanup is handled by base classes. Larvae transition to prepupae upon completing development rather than being destroyed.
Definition at line 1815 of file Osmia_dox.cpp.
Member Function Documentation
DailyMortality()
virtual bool Osmia_Larva::DailyMortality () inline protected virtual
Daily mortality test for larvae.
Returns
true if dies, false if survives
Uses m_DailyDevelopmentMortLarvae (0.0014), identical to egg mortality. Temperature- independent despite some evidence that provision quality (temperature-affected) influences survival.
Reimplemented from Osmia_Egg.
Reimplemented in Osmia_Prepupa, and Osmia_Pupa.
Definition at line 294 of file Osmia_enh_PART2_LifeStages.h.
References Osmia_Base::m_DailyDevelopmentMortLarvae.
Referenced by st_Develop().
ReInit()
void Osmia_Larva::ReInit (struct_Osmia * data) virtual
Reinitialize larva object from object pool.
Reinitialize an existing Osmia_Larva object with new data.
Parameters
data New initialization data
Chains to Osmia_Egg::ReInit() as larvae inherit all egg state variables without additional larva-specific initialization requirements.
Parameters
data Pointer to struct_Osmia containing new initialization data
Implementation Notes
Larvae use the same state variables as eggs (m_AgeDegrees for development tracking, m_Sex, m_OurNest, m_StageAge), but with different developmental parameters (LDT = 4.5°C, SET = 422 DD) and mortality rates (0.14% daily).
Reimplemented from Osmia_Egg.
Reimplemented in Osmia_Female, Osmia_InCocoon, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 1805 of file Osmia_dox.cpp.
References Osmia_Egg::ReInit().
Referenced by Osmia_Larva(), and Osmia_Prepupa::ReInit().
st_Develop()
TTypeOfOsmiaState Osmia_Larva::st_Develop (void) protected virtual
Development state - accumulate degree-days toward prepupation.
Execute daily larval development and mortality.
Returns
Next state (st_Prepupate if threshold reached, st_Develop to continue, or st_Die)
Development logic parallel to egg stage but with larval parameters:
Add DD if T > m_OsmiaLarvaDevelThreshold (4.5°C)
Check if total DD >= (egg DD + larva DD requirements)
Transition to prepupa or continue development
Apply daily mortality test
Biological Process
During larval development, individual progresses through instars (not explicitly modelled), consuming provision mass and growing. Final instar larva spins silk cocoon within cell, marking transition to prepupal stage.
Implementation Note
The cumulative DD check (egg + larva requirements) means early hatching (warm egg conditions) can lead to slightly shorter larval duration and vice versa, creating realistic thermal integration across stages.
Accumulates degree-days based on daily temperature and larval developmental threshold (4.5°C). Checks background mortality (0.14% daily). Returns state indicating whether to continue feeding, prepupate, or die.
Returns
Next state: toOsmias_Die if mortality occurs, toOsmias_NextStage if development completes (422 DD accumulated), toOsmias_Develop to continue feeding
Biological Rationale
Larval development follows degree-day accumulation with LDT = 4.5°C (calibrated from original 8.5°C) and SET = 422 DD. The lower threshold permits development during cool spring conditions, improving field realism. Development only occurs in sealed nests (mothers have completed provisioning), as unsealed cells may have temperature fluctuations or incomplete provisions.
Implementation Details
Temperature retrieval uses m_OurLandscape->SupplyTemp() to get current daily temperature. This differs slightly from eggs which use m_TempToday, but both access the same underlying temperature data. The degree-day calculation is identical to eggs: DD = max(0, temperature - threshold).
Mortality
Daily mortality check occurs only in sealed nests. Unsealed nests represent active provisioning where mortality risk is handled differently (primarily through parasitism and pesticide exposure mechanisms affecting the provisioning mother). The 0.14% daily rate represents background mortality from developmental failures, pollen quality issues, or microbial contamination.
Feeding Biology
While the model abstracts larval feeding into degree-day accumulation, biologically larvae are actively consuming pollen-nectar provisions, progressing through five instars. The provision mass was accumulated by the mother during nest provisioning; the larva does not forage independently. Final body mass at prepupation determines adult body mass through the provision-to-adult-mass conversion equation.
Sensitivity
Larval development duration (typically 14-21 days) makes this stage moderately sensitive to both developmental rate and mortality parameters. Cumulative mortality can reach 2-3% over the larval period, representing a modest but non-negligible population bottleneck.
See also
DailyMortality() for mortality calculation
cfg_OsmiaLarvaDevelThreshold for LDT parameter (4.5°C)
cfg_OsmiaLarvaDevelTotalDD for SET parameter (422 DD)
Reimplemented from Osmia_Egg.
Reimplemented in Osmia_Female, Osmia_InCocoon, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 1936 of file Osmia_dox.cpp.
References DailyMortality(), Osmia_Base::m_Age, Osmia_Egg::m_AgeDegrees, Osmia_Base::m_OsmiaLarvaDevelThreshold, Osmia_Base::m_OsmiaLarvaDevelTotalDD, Osmia_Base::m_OurNest, toOsmias_Develop, toOsmias_Die, and toOsmias_NextStage.
Referenced by Step().
st_Prepupate()
TTypeOfOsmiaState Osmia_Larva::st_Prepupate (void) protected virtual
Transition state - metamorphose from larva to prepupa.
Execute prepupation, creating prepupa and removing larva.
Returns
Next state (st_Die as larva object is deleted)
Prepupation sequence:
Signal population manager to create Osmia_Prepupa object
Transfer attributes (sex, mass, nest, age, DD, parasitism)
Update nest cell pointer to new prepupa
Delete larva object
Prepupa begins time-based development (not DD-based)
Biological Transition
Final instar larva completes feeding, voids gut, spins cocoon, and enters prepupal diapause. This is a major physiological transition from feeding to dormancy, preparing for metamorphosis to adult form.
Creates a new Osmia_Prepupa object inheriting all state from the larva, then removes the larva object from simulation. Represents the transition from feeding to non-feeding stages.
Returns
toOsmias_Emerged (return value not used as object is destroyed)
Biological Context
Prepupation marks the end of the feeding period. The larva has consumed its provision mass and reached final larval instar body mass. The transition to prepupa involves ceasing feeding, voiding gut contents (producing meconium), and beginning cocoon construction. These behaviours are abstracted into the prepupa stage rather than explicitly modelled.
State Transfer
All critical state transfers to the prepupa: body mass (determines adult size), sex (fixed at oviposition), parasitism status (contamination during provisioning), nest association, and accumulated age. The prepupa will use a different developmental model (time-based rather than degree-day) reflecting the unique biology of this transitional stage.
Model Outputs
Records larval stage duration under OSMIATESTING compilation for model verification. Larval duration is a key phenological metric that should match field observations for model validation.
See also
Osmia_Prepupa constructor for prepupa initialization
struct_Osmia for state transfer data structure
Creates a new prepupa object and passes the data from the larva to it, then signals young object removal.
Definition at line 1973 of file Osmia_dox.cpp.
References struct_Osmia::age, struct_Osmia::L, Osmia_Base::m_Age, Osmia_Base::m_Mass, Osmia_Base::m_OurNest, Osmia_Base::m_OurPopulationManager, Osmia_Base::m_ParasitoidStatus, Osmia_Egg::m_Sex, Osmia_Egg::m_StageAge, struct_Osmia::mass, struct_Osmia::nest, struct_Osmia::OPM, struct_Osmia::parasitised, struct_Osmia::sex, to_OsmiaPrepupa, toOsmias_Emerged, struct_Osmia::x, and struct_Osmia::y.
Referenced by Step().
Step()
void Osmia_Larva::Step (void) virtual
Main step function executing larval behaviour.
Execute daily time step for larva agent.
Very similar to egg step: calls st_Develop for degree-day accumulation, tests daily mortality, transitions to prepupa when threshold reached.
Implements state machine controlling larval behaviour. Larvae primarily call st_Develop() to accumulate degree-days through the feeding period until prepupation. State machine structure parallels egg behaviour but transitions to prepupa rather than larva.
State Machine Logic
toOsmias_InitialState: Entry point, transitions immediately to Develop
toOsmias_Develop: Accumulates degree-days through feeding instars, checks mortality
toOsmias_NextStage: Triggers prepupation via st_Prepupate(), creating prepupa object
toOsmias_Die: Executes death, removes from nest and simulation
Biological Context
During development, larvae consume the provision mass, progressing through five instars with periodic moulting. The degree-day model abstracts these discrete moults into continuous development. Mortality during larval feeding (0.14% daily) represents failures in provision consumption, developmental abnormalities, or pathogen infections.
See also
st_Develop() for degree-day accumulation
st_Prepupate() for transition to prepupal stage
Osmia larva behaviour is simple. It calls develop until the larva prepupates or dies.
Reimplemented from Osmia_Egg.
Reimplemented in Osmia_Female, Osmia_InCocoon, Osmia_Prepupa, and Osmia_Pupa.
Definition at line 1866 of file Osmia_dox.cpp.
References Osmia_Base::m_CurrentOState, st_Develop(), Osmia_Base::st_Dying(), st_Prepupate(), toOsmias_Develop, toOsmias_Die, toOsmias_InitialState, and toOsmias_NextStage.
The documentation for this class was generated from the following files:
src/Osmia_enh_PART2_LifeStages.h
src/Osmia_dox.cpp
src/Osmia_enhanced.cpp