Osmia bicornis Population Model: OsmiaParasitoidSubPopulation Class Reference
OsmiaParasitoidSubPopulation Class Reference
Spatially-explicit sub-population for a single parasitoid species.
#include <Osmia_Population_Manager_dox.h>
Public Member Functions
OsmiaParasitoidSubPopulation (double a_dispersalfraction, double a_startno, int a_x, int a_y, int a_wide, int a_high, OsmiaParasitoid_Population_Manager *a_popman)
Constructor initializing spatial position and dispersal parameters.
~OsmiaParasitoidSubPopulation ()
Destructor.
void Add (double a_change)
Add parasitoids (e.g., immigrants from neighbours).
void Remove (double a_change)
Remove parasitoids (e.g., mortality, emigration).
double GetSubPopnSize ()
Query current population size.
void DailyMortality ()
Apply daily mortality.
void Dispersal ()
Execute dispersal to neighbouring cells.
void Reproduce ()
Execute reproduction based on local host density.
virtual void DoFirst ()
Main daily update orchestrating sub-population processes.
void SetThisMonth (int a_month)
Update current month for mortality lookup.
void SetMortalities (array< double, 12 > a_morts)
Set monthly mortality rates array.
Protected Attributes
double m_NoParasitoids
Current number of parasitoids in this spatial cell.
double m_DiffusionRate
Proportion of population dispersing per time step.
double m_DiffusionConstant
Distance-dependent dispersal kernel parameter.
int m_CellIndexArray [8]
Pre-calculated indices of 8 neighbouring cells (Moore neighbourhood).
int m_x
Grid X-coordinate of this cell.
int m_y
Grid Y-coordinate of this cell.
OsmiaParasitoid_Population_Manager * m_OurPopulationManager
Pointer to owning population manager.
Static Protected Attributes
static array< double, 12 > m_MortalityPerMonth = { 0,0,0,0,0,0,0,0,0,0,0,0 }
Monthly mortality rates (proportion dying per day).
static int m_ThisMonth = -1
Current month index (0-11).
Detailed Description
Spatially-explicit sub-population for a single parasitoid species.
Represents a spatial cell in the parasitoid population grid, tracking local parasitoid density and handling daily processes (mortality, dispersal, reproduction). Multiple sub-populations tile the landscape to create spatial heterogeneity in parasitism risk.
Biological Context
Osmia bicornis nests are parasitised by various insects including bombylid flies (e.g., Anthrax anthrax) and chrysidid wasps. Parasitoid populations exhibit their own spatial dynamics, dispersing between areas and responding to local host density. This class implements a simplified parasitoid model that can optionally replace the simpler probability-based parasitism in the core model.
Mechanistic vs. Probability-Based Parasitism
The model supports two parasitism approaches:
Probability-based (default): Parasitism risk is a simple function of cell open time
Mechanistic (this class): Parasitism emerges from explicit parasitoid population dynamics
The mechanistic approach adds realism (parasitoid dispersal, local aggregation) but increases computational cost and parameter uncertainty. Choice between approaches depends on research questions and available calibration data.
Spatial Structure
The landscape is divided into a coarse grid (e.g., 1 km² cells) with one sub-population per cell per parasitoid species. This resolution balances realism (parasitoids do show spatial structure at km scales) against computational tractability.
Implementation Note
Sub-populations managed by OsmiaParasitoid_Population_Manager which handles the spatial array and coordinates dispersal between neighbouring cells. See that class for grid structure details.
See also
OsmiaParasitoid_Population_Manager for grid management
Osmia_Female::CalcParasitised() for parasitism application to bee eggs
Definition at line 227 of file Osmia_Population_Manager_dox.h.
Constructor & Destructor Documentation
OsmiaParasitoidSubPopulation()
OsmiaParasitoidSubPopulation::OsmiaParasitoidSubPopulation (double a_dispersalfraction, double a_startno, int a_x, int a_y, int a_wide, int a_high, OsmiaParasitoid_Population_Manager * a_popman)
Constructor initializing spatial position and dispersal parameters.
Parameters
a_dispersalfraction Daily dispersal rate (proportion leaving cell)
a_startno Initial parasitoid count in this cell
a_x Grid X-coordinate
a_y Grid Y-coordinate
a_wide Total grid width (cells)
a_high Total grid height (cells)
a_popman Pointer to owning population manager
Calculates neighbour indices considering boundaries (edge cells have fewer neighbours). Initializes parasitoid count, stores spatial position.
~OsmiaParasitoidSubPopulation()
OsmiaParasitoidSubPopulation::~OsmiaParasitoidSubPopulation ()
Destructor.
Member Function Documentation
Add()
void OsmiaParasitoidSubPopulation::Add (double a_change) inline
Add parasitoids (e.g., immigrants from neighbours).
Parameters
a_change Number of parasitoids to add
Definition at line 325 of file Osmia_Population_Manager_dox.h.
References m_NoParasitoids.
DailyMortality()
void OsmiaParasitoidSubPopulation::DailyMortality ()
Apply daily mortality.
Removes proportion m_MortalityPerMonth[m_ThisMonth] of population. Stochastic mortality at individual level; deterministic at population level.
Referenced by DoFirst().
Dispersal()
void OsmiaParasitoidSubPopulation::Dispersal ()
Execute dispersal to neighbouring cells.
Calculates emigration (m_NoParasitoids × m_DiffusionRate), distributes emigrants to neighbours using distance kernel (m_DiffusionConstant). Updates both this cell and neighbour cells through population manager interface.
Referenced by DoFirst().
DoFirst()
virtual void OsmiaParasitoidSubPopulation::DoFirst () inline virtual
Main daily update orchestrating sub-population processes.
Calls processes in biologically meaningful order:
DailyMortality() - deaths from all causes
Dispersal() - movement of survivors
Reproduce() - offspring production
Virtual to allow derived classes to modify or extend process sequence.
Definition at line 371 of file Osmia_Population_Manager_dox.h.
References DailyMortality(), Dispersal(), and Reproduce().
GetSubPopnSize()
double OsmiaParasitoidSubPopulation::GetSubPopnSize () inline
Query current population size.
Returns
Number of parasitoids in this cell
Definition at line 337 of file Osmia_Population_Manager_dox.h.
References m_NoParasitoids.
Remove()
void OsmiaParasitoidSubPopulation::Remove (double a_change) inline
Remove parasitoids (e.g., mortality, emigration).
Parameters
a_change Number of parasitoids to remove
Definition at line 331 of file Osmia_Population_Manager_dox.h.
References m_NoParasitoids.
Reproduce()
void OsmiaParasitoidSubPopulation::Reproduce ()
Execute reproduction based on local host density.
Queries landscape for local Osmia nest density, calculates offspring production using functional response, adds offspring to population. Reproduction success depends on host encounter rate (search efficiency × host density).
Referenced by DoFirst().
SetMortalities()
void OsmiaParasitoidSubPopulation::SetMortalities (array< double, 12 > a_morts) inline
Set monthly mortality rates array.
Parameters
a_morts Array of 12 monthly mortality values
Called during initialization by population manager after reading configuration file. Static array shared across all sub-populations.
Definition at line 389 of file Osmia_Population_Manager_dox.h.
References m_MortalityPerMonth.
SetThisMonth()
void OsmiaParasitoidSubPopulation::SetThisMonth (int a_month) inline
Update current month for mortality lookup.
Parameters
a_month Month index (0-11, where 0=January)
Definition at line 381 of file Osmia_Population_Manager_dox.h.
References m_ThisMonth.
Member Data Documentation
m_CellIndexArray
int OsmiaParasitoidSubPopulation::m_CellIndexArray[8] protected
Pre-calculated indices of 8 neighbouring cells (Moore neighbourhood).
Performance optimization: storing neighbour indices avoids repeated coordinate-to-index calculations during dispersal. Calculated once during construction, handling edge cases (boundary cells have fewer neighbours).
Definition at line 263 of file Osmia_Population_Manager_dox.h.
m_DiffusionConstant
double OsmiaParasitoidSubPopulation::m_DiffusionConstant protected
Distance-dependent dispersal kernel parameter.
Controls how dispersal probability decays with distance. Higher values indicate shorter-distance movements (more local aggregation). Typically estimated from mark-recapture or genetic data, but often calibrated due to data limitations.
Definition at line 255 of file Osmia_Population_Manager_dox.h.
m_DiffusionRate
double OsmiaParasitoidSubPopulation::m_DiffusionRate protected
Proportion of population dispersing per time step.
Daily diffusion rate (0-1 scale). Represents innate dispersal tendency independent of distance travelled. Biological basis: parasitoids show consistent movement rates even in uniform host environments, suggesting intrinsic dispersal motivation (Van Nouhuys and Hanski 2002).
Definition at line 247 of file Osmia_Population_Manager_dox.h.
m_MortalityPerMonth
array< double, 12 > OsmiaParasitoidSubPopulation::m_MortalityPerMonth = { 0,0,0,0,0,0,0,0,0,0,0,0 } static protected
Monthly mortality rates (proportion dying per day).
Static array shared across all sub-populations, read from configuration. Monthly resolution acknowledges seasonal variation in parasitoid survival (higher mortality during unfavourable weather periods). Daily application allows flexible phenology without discrete monthly boundaries.
Data Requirements
Ideally derived from field studies tracking parasitoid survival across seasons. In practice, often calibrated to match observed parasitism patterns in bee populations.
Definition at line 1338 of file Osmia_Population_Manager_dox.h.
Referenced by SetMortalities().
m_NoParasitoids
double OsmiaParasitoidSubPopulation::m_NoParasitoids protected
Current number of parasitoids in this spatial cell.
Continuous (double) to allow fractional individuals, avoiding discretization artifacts in dispersal and mortality. Biological interpretation: expected number of parasitoids, acknowledging spatial sampling stochasticity.
Definition at line 238 of file Osmia_Population_Manager_dox.h.
Referenced by Add(), GetSubPopnSize(), and Remove().
m_OurPopulationManager
OsmiaParasitoid_Population_Manager* OsmiaParasitoidSubPopulation::m_OurPopulationManager protected
Pointer to owning population manager.
Allows sub-population to access manager methods (add dispersers to neighbours, query landscape state). Necessary because dispersal affects multiple sub-populations and requires manager-level coordination.
Definition at line 277 of file Osmia_Population_Manager_dox.h.
m_ThisMonth
int OsmiaParasitoidSubPopulation::m_ThisMonth = -1 static protected
Current month index (0-11).
Static optimization: all sub-populations experience same month, so single shared variable avoids repeated date queries. Updated by population manager.
Definition at line 297 of file Osmia_Population_Manager_dox.h.
Referenced by SetThisMonth().
m_x
int OsmiaParasitoidSubPopulation::m_x protected
Grid X-coordinate of this cell.
Definition at line 266 of file Osmia_Population_Manager_dox.h.
m_y
int OsmiaParasitoidSubPopulation::m_y protected
Grid Y-coordinate of this cell.
Definition at line 269 of file Osmia_Population_Manager_dox.h.
The documentation for this class was generated from the following files:
src/Osmia_Population_Manager_dox.h
src/Osmia_Population_Manager_dox.cpp